// This file was generated by generate-services.ts on 2025-07-17 11:35:22
import { PerformanceSheetVersion } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type PerformanceSheetVersionAttributes = Omit<PerformanceSheetVersion, "id" | "createdAt" | "updatedAt">;

export class PerformanceSheetVersionService extends BaseService<PerformanceSheetVersion> {
	protected model = prisma.performanceSheetVersion;
	protected entityName = "PerformanceSheetVersion";
	protected modelName = "performanceSheetVersion";

	protected async validate(entity: PerformanceSheetVersionAttributes): Promise<void> {
		if (!entity.fields) throw new BadRequestError("fields is required");
	}
}
