services:
  app:
    build: .
    ports:
      - "5173:5173"
      - "8080:8080"
      - "6379:6379"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/client/node_modules
      - /app/apps/server/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:password@host.docker.internal:5432/quote_dev
