export const DAYS_PER_WEEK_OPTIONS = [
  { value: "1", label: "1 Day" },
  { value: "2", label: "2 Days" },
  { value: "3", label: "3 Days" },
  { value: "4", label: "4 Days" },
  { value: "5", label: "5 Days" },
  { value: "6", label: "6 Days" },
  { value: "7", label: "7 Days" },
];

export const YES_NO_OPTIONS = [
  { value: "yes", label: "Yes" },
  { value: "no", label: "No" },
];

export const LINE_TYPE_OPTIONS = [
  { value: "new", label: "New Line" },
  { value: "retrofit", label: "Retrofit" },
  { value: "upgrade", label: "Upgrade" },
];

export const PULL_THRU_OPTIONS = [
  { value: "yes", label: "Yes" },
  { value: "no", label: "No" },
];

export const COIL_LOADING_OPTIONS = [
  { value: "Operator Side", label: "Operator Side" },
  { value: "Non-Operator Side", label: "Non-Operator Side" },
];

export const MATERIAL_TYPE_OPTIONS = [
  { value: "Aluminum", label: "Aluminum" },
  { value: "Galvanized", label: "Galvanized" },
  { value: "HS Steel", label: "HS Steel" },
  { value: "Hot Rolled Steel", label: "Hot Rolled Steel" },
  { value: "Dual Phase", label: "Dual Phase" },
  { value: "Cold Rolled Steel", label: "Cold Rolled Steel" },
  { value: "Sainless Steel", label: "Stainless Steel" },
  { value: "Titanium", label: "Titanium" },
  { value: "Brass", label: "Brass" },
  { value: "Beryl Copper", label: "Beryl Copper" },
];

export const CONTROLS_LEVEL_OPTIONS = [
  { value: "Mini-Drive System", label: "Mini-Drive System" },
  { value: "Relay Machine", label: "Relay Machine" },
  { value: "SyncMaster", label: "SyncMaster" },
  { value: "IP Indexer Basic", label: "IP Indexer Basic" },
  { value: "Allen Bradley Basic", label: "Allen Bradley Basic" },
  { value: "SyncMaster Plus", label: "SyncMaster Plus" },
  { value: "IP Indexer Plus", label: "IP Indexer Plus" },
  { value: "Allen Bradley Plus", label: "Allen Bradley Plus" },
  { value: "Fully Automatic", label: "Fully Automatic" },
];

export const FEED_DIRECTION_OPTIONS = [
  { value: "left-to-right", label: "Left to Right" },
  { value: "right-to-left", label: "Right to Left" },
];

export const ROLL_TYPE_OPTIONS = [
  { value: "7 Roll Str. Backbend", label: "7 Roll Str. Backbend" },
  { value: "9 Roll Str. Backbend", label: "9 Roll Str. Backbend" },
  { value: "11 Roll Str. Backbend", label: "11 Roll Str. Backbend" },
];

export const BACKPLATE_TYPE_OPTIONS = [
  { value: "standard", label: "Standard" },
  { value: "quick-change", label: "Quick Change" },
  { value: "hydraulic", label: "Hydraulic" },
];

export const REEL_STYLE_OPTIONS = [
  { value: "single", label: "Single Reel" },
  { value: "dual", label: "Dual Reel" },
  { value: "turret", label: "Turret Style" },
];

export const REEL_MODEL_OPTIONS = [
  { value: "6", label: "6" },
  { value: "8", label: "8" },
  { value: "10", label: "10" },
  { value: "12", label: "12" },
  { value: "14", label: "14" },
  { value: "16", label: "16" },
  { value: "18", label: "18" },
  { value: "20", label: "20" },
];

export const REEL_WIDTH_OPTIONS = [
  { value: "12", Label: "12" },
  { value: "18", Label: "18" },
  { value: "24", Label: "24" },
  { value: "30", Label: "30" },
  { value: "36", Label: "36" },
  { value: "42", Label: "42" },
  { value: "48", Label: "48" },
  { value: "54", Label: "54" },
  { value: "60", Label: "60" },
  { value: "66", Label: "66" },
  { value: "72", Label: "72" },
];

export const BACKPLATE_DIAMETER_OPTIONS = [
  { value: "11.75", Label: "11.75" },
  { value: "13.5", Label: "13.5" },
  { value: "15.5", Label: "15.5" },
  { value: "17.5", Label: "17.5" },
  { value: "19.5", Label: "19.5" },
];

export const HYDRAULIC_THREADING_DRIVE_OPTIONS = [
  { value: "none", label: "None" },
  { value: "standard", label: "Standard" },
  { value: "high-torque", label: "High Torque" },
];

export const HOLD_DOWN_ASSY_OPTIONS = [
  { value: "none", label: "None" },
  { value: "pneumatic", label: "Pneumatic" },
  { value: "hydraulic", label: "Hydraulic" },
  { value: "spring-loaded", label: "Spring Loaded" },
];

export const BRAKE_MODEL_OPTIONS = [
  { value: "DB-10", label: "DB-10" },
  { value: "DB-15", label: "DB-15" },
  { value: "DB-20", label: "DB-20" },
  { value: "DB-25", label: "DB-25" },
  { value: "DB-30", label: "DB-30" },
];

export const BRAKE_QUANTITY_OPTIONS = [
  { value: "1", label: "1" },
  { value: "2", label: "2" },
  { value: "3", label: "3" },
  { value: "4", label: "4" },
];

export const RFQ_PERFORMANCE_SHEET_SEED = {
  id: "tab-rfq",
  label: "RFQ",
  value: "rfq",
  sequence: 1,
  sections: [
    {
      id: "section-basic-info",
      title: "Basic Information",
      sequence: 1,
      columns: 4,
      fields: [
        {
          id: "referenceNumber",
          label: "Reference Number",
          type: "text",
          size: 1,
          sequence: 1,
          required: true,
        },
        {
          id: "rfq.dates.date",
          label: "RFQ Date",
          type: "date",
          size: 1,
          sequence: 2,
          required: true,
          default: new Date().toISOString().split("T")[0],
        },
        {
          id: "common.customer",
          label: "Customer",
          type: "text",
          size: 1,
          sequence: 3,
          required: true,
        },
        {
          id: "common.customerInfo.contactName",
          label: "Contact Name",
          type: "text",
          size: 1,
          sequence: 4,
          required: true,
        },
        {
          id: "common.customerInfo.position",
          label: "Position",
          type: "text",
          size: 1,
          sequence: 5,
          required: true,
        },
        {
          id: "common.customerInfo.phoneNumber",
          label: "Phone Number",
          type: "text",
          size: 1,
          sequence: 6,
          required: true,
        },
        {
          id: "common.customerInfo.email",
          label: "Email",
          type: "text",
          size: 1,
          sequence: 7,
          required: true,
        },
        {
          id: "common.customerInfo.streetAddress",
          label: "Street Address",
          type: "text",
          size: 2,
          sequence: 8,
          required: true,
        },
        {
          id: "common.customerInfo.city",
          label: "City",
          type: "text",
          size: 1,
          sequence: 9,
          required: true,
        },
        {
          id: "common.customerInfo.state",
          label: "State",
          type: "text",
          size: 1,
          sequence: 10,
          required: true,
        },
        {
          id: "common.customerInfo.zip",
          label: "ZIP Code",
          type: "text",
          size: 1,
          sequence: 11,
          required: true,
        },
        {
          id: "common.customerInfo.country",
          label: "Country",
          type: "text",
          size: 1,
          sequence: 12,
          required: true,
        },
        {
          id: "common.customerInfo.dealerName",
          label: "Dealer Name",
          type: "text",
          size: 1,
          sequence: 13,
          required: true,
        },
        {
          id: "common.customerInfo.dealerSalesman",
          label: "Dealer Salesman",
          type: "text",
          size: 1,
          sequence: 14,
          required: true,
        },
        {
          id: "rfq.dates.idealDeliveryDate",
          label: "Ideal Delivery Date",
          type: "date",
          size: 1,
          sequence: 15,
          required: true,
        },
        {
          id: "rfq.dates.decisionDate",
          label: "Decision Date",
          type: "date",
          size: 1,
          sequence: 16,
          required: true,
        },
      ],
    },
    {
      id: "section-line-config",
      title: "Line Configuration",
      sequence: 2,
      columns: 4,
      fields: [
        {
          id: "feed.feed.application",
          label: "Application",
          type: "text",
          size: 2,
          sequence: 1,
          required: true,
        },
        {
          id: "common.equipment.feed.lineType",
          label: "Line Type",
          type: "select",
          size: 1,
          sequence: 2,
          required: true,
          options: LINE_TYPE_OPTIONS,
        },
        {
          id: "feed.feed.pullThru.isPullThru",
          label: "Pull Through",
          type: "select",
          size: 1,
          sequence: 3,
          required: true,
          options: PULL_THRU_OPTIONS,
        },
        {
          id: "rfq.runningCosmeticMaterial",
          label: "Running Cosmetic Material",
          type: "select",
          size: 1,
          sequence: 4,
          required: true,
          options: YES_NO_OPTIONS,
        },
      ],
    },
    {
      id: "section-coil-specs",
      title: "Coil Specifications",
      sequence: 3,
      columns: 4,
      fields: [
        {
          id: "common.coil.maxCoilWidth",
          label: "Max Coil Width (in)",
          type: "number",
          size: 1,
          sequence: 1,
          required: true,
        },
        {
          id: "common.coil.minCoilWidth",
          label: "Min Coil Width (in)",
          type: "number",
          size: 1,
          sequence: 2,
          required: true,
        },
        {
          id: "common.coil.maxCoilOD",
          label: "Max Coil OD (in)",
          type: "number",
          size: 1,
          sequence: 3,
          required: true,
        },
        {
          id: "common.coil.coilID",
          label: "Coil ID (in)",
          type: "number",
          size: 1,
          sequence: 4,
          required: true,
        },
        {
          id: "common.coil.maxCoilWeight",
          label: "Max Coil Weight (lbs)",
          type: "number",
          size: 1,
          sequence: 5,
          required: true,
        },
        {
          id: "rfq.coil.slitEdge",
          label: "Slit Edge",
          type: "select",
          size: 1,
          sequence: 6,
          required: true,
          options: YES_NO_OPTIONS,
        },
        {
          id: "rfq.coil.millEdge",
          label: "Mill Edge",
          type: "select",
          size: 1,
          sequence: 7,
          required: true,
          options: YES_NO_OPTIONS,
        },
        {
          id: "rfq.coil.requireCoilCar",
          label: "Require Coil Car",
          type: "select",
          size: 1,
          sequence: 8,
          required: true,
          options: YES_NO_OPTIONS,
        },
        {
          id: "rfq.coil.runningOffBackplate",
          label: "Running Off Backplate",
          type: "select",
          size: 1,
          sequence: 9,
          required: true,
          options: YES_NO_OPTIONS,
        },
        {
          id: "rfq.coil.requireRewinding",
          label: "Require Rewinding",
          type: "select",
          size: 1,
          sequence: 10,
          required: true,
          options: YES_NO_OPTIONS,
        },
        {
          id: "rfq.coil.changeTimeConcern",
          label: "Change Time Concern",
          type: "select",
          size: 1,
          sequence: 11,
          required: true,
          options: YES_NO_OPTIONS,
        },
        {
          id: "rfq.coil.loading",
          label: "Coil Loading Method",
          type: "select",
          size: 1,
          sequence: 12,
          required: true,
          options: COIL_LOADING_OPTIONS,
        },
      ],
    },
    {
      id: "section-material-specs",
      title: "Material Specifications",
      sequence: 4,
      columns: 4,
      fields: [
        {
          id: "common.material.materialThickness",
          label: "Material Thickness (in)",
          type: "number",
          size: 1,
          sequence: 1,
          required: true,
        },
        {
          id: "common.material.coilWidth",
          label: "Coil Width (in)",
          type: "number",
          size: 1,
          sequence: 2,
          required: true,
        },
        {
          id: "common.material.materialType",
          label: "Material Type",
          type: "select",
          size: 1,
          sequence: 3,
          required: true,
          options: MATERIAL_TYPE_OPTIONS,
        },
        {
          id: "common.material.maxYieldStrength",
          label: "Max Yield Strength (PSI)",
          type: "number",
          size: 1,
          sequence: 4,
          required: true,
        },
      ],
    },
    {
      id: "section-equipment-config",
      title: "Equipment Configuration",
      sequence: 5,
      columns: 4,
      fields: [
        {
          id: "common.equipment.feed.controlsLevel",
          label: "Controls Level",
          type: "select",
          size: 1,
          sequence: 1,
          required: true,
          options: CONTROLS_LEVEL_OPTIONS,
        },
        {
          id: "common.equipment.feed.typeOfLine",
          label: "Type of Line",
          type: "text",
          size: 1,
          sequence: 2,
          required: true,
        },
        {
          id: "common.equipment.feed.passline",
          label: "Passline Height (in)",
          type: "number",
          size: 1,
          sequence: 3,
          required: true,
        },
        {
          id: "common.equipment.feed.direction",
          label: "Feed Direction",
          type: "select",
          size: 1,
          sequence: 4,
          required: true,
          options: FEED_DIRECTION_OPTIONS,
        },
        {
          id: "common.equipment.straightener.rollType",
          label: "Straightener Roll Type",
          type: "select",
          size: 1,
          sequence: 5,
          required: true,
          options: ROLL_TYPE_OPTIONS,
        },
        {
          id: "materialSpecs.reel.backplate.type",
          label: "Backplate Type",
          type: "select",
          size: 1,
          sequence: 6,
          required: true,
          options: BACKPLATE_TYPE_OPTIONS,
        },
        {
          id: "materialSpecs.reel.style",
          label: "Reel Style",
          type: "select",
          size: 1,
          sequence: 7,
          required: true,
          options: REEL_STYLE_OPTIONS,
        },
      ],
    },
    {
      id: "section-press-info",
      title: "Press Information",
      sequence: 6,
      columns: 4,
      fields: [
        {
          id: "rfq.press.maxSPM",
          label: "Max SPM",
          type: "number",
          size: 1,
          sequence: 1,
          required: true,
        },
      ],
    },
    {
      id: "section-dies-info",
      title: "Dies Information",
      sequence: 7,
      columns: 4,
      fields: [
        {
          id: "rfq.dies.transferDies",
          label: "Transfer Dies",
          type: "select",
          size: 1,
          sequence: 1,
          required: true,
          options: YES_NO_OPTIONS,
        },
        {
          id: "rfq.dies.progressiveDies",
          label: "Progressive Dies",
          type: "select",
          size: 1,
          sequence: 2,
          required: true,
          options: YES_NO_OPTIONS,
        },
        {
          id: "rfq.dies.blankingDies",
          label: "Blanking Dies",
          type: "select",
          size: 1,
          sequence: 3,
          required: true,
          options: YES_NO_OPTIONS,
        },
      ],
    },
    {
      id: "section-feed-requirements",
      title: "Feed Requirements",
      sequence: 8,
      columns: 4,
      fields: [
        {
          id: "feed-requirements-header",
          label: "Average Feed Rates",
          type: "text",
          size: 4,
          sequence: 1,
          required: false,
        },
        {
          id: "common.feedRates.average.length",
          label: "Average Length (in)",
          type: "number",
          size: 1,
          sequence: 2,
          required: true,
        },
        {
          id: "common.feedRates.average.spm",
          label: "Average SPM",
          type: "number",
          size: 1,
          sequence: 3,
          required: true,
        },
        {
          id: "common.feedRates.average.fpm",
          label: "Average FPM",
          type: "number",
          size: 1,
          sequence: 4,
          required: true,
        },
        {
          id: "feed-requirements-max-header",
          label: "Maximum Feed Rates",
          type: "text",
          size: 4,
          sequence: 5,
          required: false,
        },
        {
          id: "common.feedRates.max.length",
          label: "Max Length (in)",
          type: "number",
          size: 1,
          sequence: 6,
          required: true,
        },
        {
          id: "common.feedRates.max.spm",
          label: "Max SPM",
          type: "number",
          size: 1,
          sequence: 7,
          required: true,
        },
        {
          id: "common.feedRates.max.fpm",
          label: "Max FPM",
          type: "number",
          size: 1,
          sequence: 8,
          required: true,
        },
        {
          id: "feed-requirements-min-header",
          label: "Minimum Feed Rates",
          type: "text",
          size: 4,
          sequence: 9,
          required: false,
        },
        {
          id: "common.feedRates.min.length",
          label: "Min Length (in)",
          type: "number",
          size: 1,
          sequence: 10,
          required: true,
        },
        {
          id: "common.feedRates.min.spm",
          label: "Min SPM",
          type: "number",
          size: 1,
          sequence: 11,
          required: true,
        },
        {
          id: "common.feedRates.min.fpm",
          label: "Min FPM",
          type: "number",
          size: 1,
          sequence: 12,
          required: true,
        },
      ],
    },
    {
      id: "section-space-mounting",
      title: "Space & Mounting Requirements",
      sequence: 9,
      columns: 4,
      fields: [
        {
          id: "rfq.equipmentSpaceLength",
          label: "Equipment Space Length (ft)",
          type: "number",
          size: 1,
          sequence: 1,
          required: true,
        },
        {
          id: "rfq.equipmentSpaceWidth",
          label: "Equipment Space Width (ft)",
          type: "number",
          size: 1,
          sequence: 2,
          required: true,
        },
        {
          id: "rfq.obstructions",
          label: "Obstructions",
          type: "textarea",
          size: 4,
          sequence: 3,
          required: true,
        },
        {
          id: "rfq.voltageRequired",
          label: "Voltage Required",
          type: "text",
          size: 1,
          sequence: 4,
          required: true,
        },
        {
          id: "rfq.requireGuarding",
          label: "Require Guarding",
          type: "select",
          size: 1,
          sequence: 5,
          required: true,
          options: YES_NO_OPTIONS,
        },
      ],
    },
    {
      id: "section-special-requirements",
      title: "Special Requirements",
      sequence: 10,
      columns: 4,
      fields: [
        {
          id: "rfq.specialRequirements",
          label: "Special Requirements & Notes",
          type: "textarea",
          size: 4,
          sequence: 1,
          required: false,
        },
      ],
    },
  ],
};

export const TDDBHD_PERFORMANCE_SHEET_SEED = {
  id: "tab-tddbhd",
  label: "TDDBHD",
  value: "tddbhd",
  sequence: 2,
  sections: [
    {
      id: "section-customer-date",
      title: "Customer & Date",
      sequence: 1,
      columns: 4,
      fields: [
        {
          id: "common.customer",
          label: "Customer",
          type: "text",
          size: 1,
          sequence: 1,
          required: false,
        },
        {
          id: "rfq.dates.date",
          label: "Date",
          type: "date",
          size: 1,
          sequence: 2,
          required: false,
        },
      ],
    },
    {
      id: "section-reel-material-specs",
      title: "Reel & Material Specs",
      sequence: 2,
      columns: 4,
      fields: [
        {
          id: "common.equipment.reel.model",
          label: "Reel Model",
          type: "select",
          size: 1,
          sequence: 1,
          required: false,
          options: REEL_MODEL_OPTIONS,
        },
        {
          id: "common.equipment.reel.width",
          label: "Reel Width",
          type: "select",
          size: 1,
          sequence: 2,
          required: false,
          options: REEL_WIDTH_OPTIONS,
        },
        {
          id: "common.equipment.reel.backplate.diameter",
          label: "Backplate Diameter",
          type: "select",
          size: 1,
          sequence: 3,
          required: false,
          options: BACKPLATE_DIAMETER_OPTIONS,
        },
        {
          id: "common.material.materialType",
          label: "Material Type",
          type: "select",
          size: 1,
          sequence: 4,
          required: false,
          options: MATERIAL_TYPE_OPTIONS,
        },
        {
          id: "common.material.coilWidth",
          label: "Material Width (in)",
          type: "number",
          size: 1,
          sequence: 5,
          required: false,
        },
        {
          id: "common.material.materialThickness",
          label: "Material Thickness (in)",
          type: "number",
          size: 1,
          sequence: 6,
          required: false,
        },
        {
          id: "common.material.maxYieldStrength",
          label: "Material Yield Strength (psi)",
          type: "number",
          size: 1,
          sequence: 7,
          required: false,
        },
        {
          id: "tddbhd.reel.airPressureAvailable",
          label: "Air Pressure Available (psi)",
          type: "number",
          size: 1,
          sequence: 8,
          required: false,
        },
        {
          id: "tddbhd.reel.requiredDecelRate",
          label: "Required Decel. Rate (ft/sec²)",
          type: "number",
          size: 1,
          sequence: 9,
          required: false,
        },
      ],
    },
    {
      id: "section-coil-brake-specs",
      title: "Coil, Brake & Other Specs",
      sequence: 3,
      columns: 4,
      fields: [
        {
          id: "tddbhd.coil.coilWeight",
          label: "Coil Weight (lbs)",
          type: "number",
          size: 1,
          sequence: 1,
          required: false,
        },
        {
          id: "tddbhd.coil.coilOD",
          label: "Coil O.D. (in)",
          type: "number",
          size: 1,
          sequence: 2,
          required: false,
        },
        {
          id: "tddbhd.reel.dispReelMtr",
          label: "Disp. (Reel) Mtr.",
          type: "text",
          size: 1,
          sequence: 3,
          required: false,
        },
        {
          id: "tddbhd.reel.webTension.psi",
          label: "Web Tension (psi)",
          type: "number",
          size: 1,
          sequence: 4,
          required: false,
        },
        {
          id: "tddbhd.reel.webTension.lbs",
          label: "Web Tension (lbs)",
          type: "number",
          size: 1,
          sequence: 5,
          required: false,
        },
        {
          id: "tddbhd.reel.brakePadDiameter",
          label: "Brake Pad Diameter (in)",
          type: "number",
          size: 1,
          sequence: 6,
          required: false,
        },
        {
          id: "tddbhd.reel.cylinderBore",
          label: "Cylinder Bore (in)",
          type: "number",
          size: 1,
          sequence: 7,
          required: false,
        },
        {
          id: "tddbhd.reel.coefficientOfFriction",
          label: "Coefficient of Friction",
          type: "number",
          size: 1,
          sequence: 8,
          required: false,
        },
      ],
    },
    {
      id: "section-threading-drive",
      title: "Threading Drive",
      sequence: 4,
      columns: 4,
      fields: [
        {
          id: "tddbhd.reel.threadingDrive.airClutch",
          label: "Air Clutch",
          type: "select",
          size: 1,
          sequence: 1,
          required: false,
          options: YES_NO_OPTIONS,
        },
        {
          id: "tddbhd.reel.threadingDrive.hydThreadingDrive",
          label: "Hyd. Threading Drive",
          type: "select",
          size: 1,
          sequence: 2,
          required: false,
          options: HYDRAULIC_THREADING_DRIVE_OPTIONS,
        },
        {
          id: "tddbhd.reel.torque.atMandrel",
          label: "Torque At Mandrel (in. lbs.)",
          type: "number",
          size: 1,
          sequence: 3,
          required: false,
        },
        {
          id: "tddbhd.reel.torque.rewindRequired",
          label: "Rewind Torque Req. (in. lbs.)",
          type: "number",
          size: 1,
          sequence: 4,
          required: false,
        },
        {
          id: "tddbhd.reel.checks.tddbhdCheck",
          label: "Passed",
          type: "text",
          size: 1,
          sequence: 5,
          required: false,
        },
      ],
    },
    {
      id: "section-hold-down",
      title: "Hold Down",
      sequence: 5,
      columns: 4,
      fields: [
        {
          id: "tddbhd.reel.holddown.assy",
          label: "Hold Down Assy",
          type: "select",
          size: 1,
          sequence: 1,
          required: false,
          options: HOLD_DOWN_ASSY_OPTIONS,
        },
        {
          id: "tddbhd.reel.holddown.cylinderPressure",
          label: "Holddown Pressure (psi)",
          type: "number",
          size: 1,
          sequence: 2,
          required: false,
        },
        {
          id: "tddbhd.reel.holddown.force.required",
          label: "Hold Down Force Required (lbs)",
          type: "number",
          size: 1,
          sequence: 3,
          required: false,
        },
        {
          id: "tddbhd.reel.holddown.force.available",
          label: "Hold Down Force Available (lbs)",
          type: "number",
          size: 1,
          sequence: 4,
          required: false,
        },
        {
          id: "tddbhd.reel.minMaterialWidth",
          label: "Min. Material Width (in)",
          type: "number",
          size: 1,
          sequence: 5,
          required: false,
        },
        {
          id: "tddbhd.reel.confirmedMinWidth",
          label: "Confirmed Min Width OK",
          type: "checkbox",
          size: 1,
          sequence: 6,
          required: false,
        },
      ],
    },
    {
      id: "section-drag-brake",
      title: "Drag Brake",
      sequence: 6,
      columns: 4,
      fields: [
        {
          id: "tddbhd.reel.dragBrake.model",
          label: "Brake Model",
          type: "select",
          size: 1,
          sequence: 1,
          required: false,
          options: BRAKE_MODEL_OPTIONS,
        },
        {
          id: "tddbhd.reel.dragBrake.quantity",
          label: "Brake Quantity",
          type: "select",
          size: 1,
          sequence: 2,
          required: false,
          options: BRAKE_QUANTITY_OPTIONS,
        },
        {
          id: "tddbhd.reel.torque.required",
          label: "Torque Required (in. lbs.)",
          type: "number",
          size: 1,
          sequence: 3,
          required: false,
        },
        {
          id: "tddbhd.reel.dragBrake.psiAirRequired",
          label: "Failsafe - Single Stage (psi air req.)",
          type: "number",
          size: 1,
          sequence: 4,
          required: false,
        },
        {
          id: "tddbhd.reel.dragBrake.holdingForce",
          label: "Failsafe Holding Force (in. lbs.)",
          type: "number",
          size: 1,
          sequence: 5,
          required: false,
        },
      ],
    },
  ],
};
