// This file was generated by generate-services.ts
import type { Activity } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type ActivityAttributes = Omit<Activity, "id" | "createdAt" | "updatedAt">;

export class ActivityRepository extends BaseRepository<Activity> {
  protected model = prisma.activity;
  protected entityName = "Activity";
  protected modelName = "activity";

  protected async validate(entity: ActivityAttributes): Promise<void> {
    if (!entity.timestamp)
      throw new BadRequestError("timestamp is required");
  }
}
