// This file was generated by generate-services.ts
import type { Asset } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type AssetAttributes = Omit<Asset, "id" | "createdAt" | "updatedAt">;

export class AssetRepository extends BaseRepository<Asset> {
  protected model = prisma.asset;
  protected entityName = "Asset";
  protected modelName = "asset";

  protected async validate(entity: AssetAttributes): Promise<void> {
    if (!entity.key)
      throw new BadRequestError("key is required");
    if (!entity.filename)
      throw new BadRequestError("filename is required");
    if (!entity.originalName)
      throw new BadRequestError("originalName is required");
    if (!entity.mimeType)
      throw new BadRequestError("mimeType is required");
    if (!entity.size)
      throw new BadRequestError("size is required");
    if (!entity.storageProvider)
      throw new BadRequestError("storageProvider is required");
    if (!entity.url)
      throw new BadRequestError("url is required");
    if (!entity.tags)
      throw new BadRequestError("tags is required");
    if (entity.isPublic === undefined || entity.isPublic === null)
      throw new BadRequestError("isPublic is required");
  }
}
