// This file was generated by generate-services.ts
import type { BugReport } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type BugReportAttributes = Omit<BugReport, "id" | "createdAt" | "updatedAt">;

export class BugReportRepository extends BaseRepository<BugReport> {
  protected model = prisma.bugReport;
  protected entityName = "BugReport";
  protected modelName = "bugReport";

  protected async validate(entity: BugReportAttributes): Promise<void> {
    if (!entity.title)
      throw new BadRequestError("title is required");
    if (!entity.description)
      throw new BadRequestError("description is required");
  }
}
