// This file was generated by generate-services.ts
import { Chat } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type ChatAttributes = Omit<Chat, "id" | "createdAt" | "updatedAt">;

export class ChatRepository extends BaseRepository<Chat> {
	protected model = prisma.chat;
	protected entityName = "Chat";
	protected modelName = "chat";

	protected async validate(entity: ChatAttributes): Promise<void> {
		if (!entity.employeeId) throw new BadRequestError("employeeId is required");
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}