// This file was generated by generate-services.ts
import type { Chat } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type ChatAttributes = Omit<Chat, "id" | "createdAt" | "updatedAt">;

export class ChatRepository extends BaseRepository<Chat> {
  protected model = prisma.chat;
  protected entityName = "Chat";
  protected modelName = "chat";

  protected async validate(entity: ChatAttributes): Promise<void> {
    if (!entity.employeeId)
      throw new BadRequestError("employeeId is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
