// This file was generated by generate-services.ts
import type { CoilType } from "@prisma/client";

import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type CoilTypeAttributes = Omit<CoilType, "id" | "createdAt" | "updatedAt">;

export class CoilTypeRepository extends BaseRepository<CoilType> {
  protected model = prisma.coilType;
  protected entityName = "CoilType";
  protected modelName = "coilType";

  protected async validate(_entity: CoilTypeAttributes): Promise<void> {
    // No required fields to validate
  }
}
