// This file was generated by generate-services.ts
import type { CompanyRelationship } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type CompanyRelationshipAttributes = Omit<CompanyRelationship, "id" | "createdAt" | "updatedAt">;

export class CompanyRelationshipRepository extends BaseRepository<CompanyRelationship> {
  protected model = prisma.companyRelationship;
  protected entityName = "CompanyRelationship";
  protected modelName = "companyRelationship";

  protected async validate(entity: CompanyRelationshipAttributes): Promise<void> {
    if (!entity.parentId)
      throw new BadRequestError("parentId is required");
    if (!entity.childId)
      throw new BadRequestError("childId is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
