// This file was generated by generate-services.ts
import { ConfigurationOption } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type ConfigurationOptionAttributes = Omit<ConfigurationOption, "id" | "createdAt" | "updatedAt">;

export class ConfigurationOptionRepository extends BaseRepository<ConfigurationOption> {
	protected model = prisma.configurationOption;
	protected entityName = "ConfigurationOption";
	protected modelName = "configurationOption";

	protected async validate(entity: ConfigurationOptionAttributes): Promise<void> {
		if (!entity.configurationId) throw new BadRequestError("configurationId is required");
		if (!entity.optionId) throw new BadRequestError("optionId is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}