// This file was generated by generate-services.ts
import type { CostCode } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type CostCodeAttributes = Omit<CostCode, "id" | "createdAt" | "updatedAt">;

export class CostCodeRepository extends BaseRepository<CostCode> {
  protected model = prisma.costCode;
  protected entityName = "CostCode";
  protected modelName = "costCode";

  protected async validate(entity: CostCodeAttributes): Promise<void> {
    if (!entity.jobSfx)
      throw new BadRequestError("jobSfx is required");
    if (!entity.bomItem)
      throw new BadRequestError("bomItem is required");
    if (!entity.sequence)
      throw new BadRequestError("sequence is required");
    if (entity.active === undefined || entity.active === null)
      throw new BadRequestError("active is required");
    if (!entity.jobCode)
      throw new BadRequestError("jobCode is required");
    if (!entity.jobName)
      throw new BadRequestError("jobName is required");
    if (!entity.needByDate)
      throw new BadRequestError("needByDate is required");
    if (entity.isConfirmed === undefined || entity.isConfirmed === null)
      throw new BadRequestError("isConfirmed is required");
  }
}
