// This file was generated by generate-services.ts
import { Department } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type DepartmentAttributes = Omit<Department, "id" | "createdAt" | "updatedAt">;

export class DepartmentRepository extends BaseRepository<Department> {
	protected model = prisma.department;
	protected entityName = "Department";
	protected modelName = "department";

	protected async validate(entity: DepartmentAttributes): Promise<void> {
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.code) throw new BadRequestError("code is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}