// This file was generated by generate-services.ts
import { Draft } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type DraftAttributes = Omit<Draft, "id" | "createdAt" | "updatedAt">;

export class DraftRepository extends BaseRepository<Draft> {
	protected model = prisma.draft;
	protected entityName = "Draft";
	protected modelName = "draft";

	protected async validate(entity: DraftAttributes): Promise<void> {
		if (!entity.entityType) throw new BadRequestError("entityType is required");
		if (!entity.data) throw new BadRequestError("data is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
	}

}