// This file was generated by generate-services.ts
import { EmailLog } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type EmailLogAttributes = Omit<EmailLog, "id" | "createdAt" | "updatedAt">;

export class EmailLogRepository extends BaseRepository<EmailLog> {
	protected model = prisma.emailLog;
	protected entityName = "EmailLog";
	protected modelName = "emailLog";

	protected async validate(entity: EmailLogAttributes): Promise<void> {
		if (!entity.to) throw new BadRequestError("to is required");
		if (!entity.subject) throw new BadRequestError("subject is required");
	}

}