// This file was generated by generate-services.ts
import type { EmployeeHours } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type EmployeeHoursAttributes = Omit<EmployeeHours, "id" | "createdAt" | "updatedAt">;

export class EmployeeHoursRepository extends BaseRepository<EmployeeHours> {
  protected model = prisma.employeeHours;
  protected entityName = "EmployeeHours";
  protected modelName = "employeeHours";

  protected async validate(entity: EmployeeHoursAttributes): Promise<void> {
    if (!entity.empNum)
      throw new BadRequestError("empNum is required");
    if (!entity.timeIn)
      throw new BadRequestError("timeIn is required");
    if (!entity.timeOut)
      throw new BadRequestError("timeOut is required");
    if (!entity.jobCode)
      throw new BadRequestError("jobCode is required");
    if (!entity.breakFlag)
      throw new BadRequestError("breakFlag is required");
    if (entity.managerApproval === undefined || entity.managerApproval === null)
      throw new BadRequestError("managerApproval is required");
    if (!entity.timeSheetMinutes)
      throw new BadRequestError("timeSheetMinutes is required");
    if (entity.nightShift === undefined || entity.nightShift === null)
      throw new BadRequestError("nightShift is required");
    if (entity.isConfirmed === undefined || entity.isConfirmed === null)
      throw new BadRequestError("isConfirmed is required");
    if (entity.hasNote === undefined || entity.hasNote === null)
      throw new BadRequestError("hasNote is required");
    if (entity.isEdited === undefined || entity.isEdited === null)
      throw new BadRequestError("isEdited is required");
  }
}
