// This file was generated by generate-services.ts
import type { ExternalAccessLink } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type ExternalAccessLinkAttributes = Omit<ExternalAccessLink, "id" | "createdAt" | "updatedAt">;

export class ExternalAccessLinkRepository extends BaseRepository<ExternalAccessLink> {
  protected model = prisma.externalAccessLink;
  protected entityName = "ExternalAccessLink";
  protected modelName = "externalAccessLink";

  protected async validate(entity: ExternalAccessLinkAttributes): Promise<void> {
    if (!entity.token)
      throw new BadRequestError("token is required");
  }
}
