// This file was generated by generate-services.ts
import { FormSection } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type FormSectionAttributes = Omit<FormSection, "id" | "createdAt" | "updatedAt">;

export class FormSectionRepository extends BaseRepository<FormSection> {
	protected model = prisma.formSection;
	protected entityName = "FormSection";
	protected modelName = "formSection";

	protected async validate(entity: FormSectionAttributes): Promise<void> {
		if (!entity.pageId) throw new BadRequestError("pageId is required");
		if (!entity.title) throw new BadRequestError("title is required");
		if (!entity.sequence) throw new BadRequestError("sequence is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}