// This file was generated by generate-services.ts
import { Form } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type FormAttributes = Omit<Form, "id" | "createdAt" | "updatedAt">;

export class FormRepository extends BaseRepository<Form> {
	protected model = prisma.form;
	protected entityName = "Form";
	protected modelName = "form";

	protected async validate(entity: FormAttributes): Promise<void> {
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}