// This file was generated by generate-services.ts
import type { Image } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type ImageAttributes = Omit<Image, "id" | "createdAt" | "updatedAt">;

export class ImageRepository extends BaseRepository<Image> {
  protected model = prisma.image;
  protected entityName = "Image";
  protected modelName = "image";

  protected async validate(entity: ImageAttributes): Promise<void> {
    if (!entity.path)
      throw new BadRequestError("path is required");
    if (!entity.uploadedAt)
      throw new BadRequestError("uploadedAt is required");
  }
}
