// This file was generated by generate-services.ts
import type { Item } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type ItemAttributes = Omit<Item, "id" | "createdAt" | "updatedAt">;

export class ItemRepository extends BaseRepository<Item> {
  protected model = prisma.item;
  protected entityName = "Item";
  protected modelName = "item";

  protected async validate(entity: ItemAttributes): Promise<void> {
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }

  protected getSearchFields(): (string | { field: string; weight: number })[] {
    return [{ field: "modelNumber", weight: 3 }, { field: "description", weight: 2 }, { field: "type", weight: 1 }];
  }
}
