// This file was generated by generate-services.ts
import type { JobCode } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type JobCodeAttributes = Omit<JobCode, "id" | "createdAt" | "updatedAt">;

export class JobCodeRepository extends BaseRepository<JobCode> {
  protected model = prisma.jobCode;
  protected entityName = "JobCode";
  protected modelName = "jobCode";

  protected async validate(entity: JobCodeAttributes): Promise<void> {
    if (!entity.jobCode)
      throw new BadRequestError("jobCode is required");
    if (!entity.description)
      throw new BadRequestError("description is required");
    if (entity.active === undefined || entity.active === null)
      throw new BadRequestError("active is required");
    if (entity.clockable === undefined || entity.clockable === null)
      throw new BadRequestError("clockable is required");
    if (entity.requiresCostCode === undefined || entity.requiresCostCode === null)
      throw new BadRequestError("requiresCostCode is required");
    if (entity.askQuantity === undefined || entity.askQuantity === null)
      throw new BadRequestError("askQuantity is required");
    if (entity.askSplitCode === undefined || entity.askSplitCode === null)
      throw new BadRequestError("askSplitCode is required");
    if (entity.isConfirmed === undefined || entity.isConfirmed === null)
      throw new BadRequestError("isConfirmed is required");
  }
}
