// This file was generated by generate-services.ts
import { JourneyInteraction } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type JourneyInteractionAttributes = Omit<JourneyInteraction, "id" | "createdAt" | "updatedAt">;

export class JourneyInteractionRepository extends BaseRepository<JourneyInteraction> {
	protected model = prisma.journeyInteraction;
	protected entityName = "JourneyInteraction";
	protected modelName = "journeyInteraction";

	protected async validate(entity: JourneyInteractionAttributes): Promise<void> {
		if (!entity.journeyId) throw new BadRequestError("journeyId is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}