// This file was generated by generate-services.ts
import { JourneyContact } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type JourneyContactAttributes = Omit<JourneyContact, "id" | "createdAt" | "updatedAt">;

export class JourneyContactRepository extends BaseRepository<JourneyContact> {
	protected model = prisma.journeyContact;
	protected entityName = "JourneyContact";
	protected modelName = "journeyContact";

	protected async validate(entity: JourneyContactAttributes): Promise<void> {
		if (!entity.journeyId) throw new BadRequestError("journeyId is required");
		if (!entity.contactId) throw new BadRequestError("contactId is required");
		if (entity.isPrimary === undefined || entity.isPrimary === null) throw new BadRequestError("isPrimary is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}