// This file was generated by generate-services.ts
import type { JourneyNote } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type JourneyNoteAttributes = Omit<JourneyNote, "id" | "createdAt" | "updatedAt">;

export class JourneyNoteRepository extends BaseRepository<JourneyNote> {
  protected model = prisma.journeyNote;
  protected entityName = "JourneyNote";
  protected modelName = "journeyNote";

  protected async validate(entity: JourneyNoteAttributes): Promise<void> {
    if (!entity.journeyId)
      throw new BadRequestError("journeyId is required");
    if (!entity.type)
      throw new BadRequestError("type is required");
    if (!entity.body)
      throw new BadRequestError("body is required");
  }
}
