// This file was generated by generate-services.ts
import type { Journey } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type JourneyAttributes = Omit<Journey, "id" | "createdAt" | "updatedAt">;

export class JourneyRepository extends BaseRepository<Journey> {
  protected model = prisma.journey;
  protected entityName = "Journey";
  protected modelName = "journey";

  protected async validate(entity: JourneyAttributes): Promise<void> {
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
