// This file was generated by generate-services.ts
import { Journey } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type JourneyAttributes = Omit<Journey, "id" | "createdAt" | "updatedAt">;

export class JourneyRepository extends BaseRepository<Journey> {
	protected model = prisma.journey;
	protected entityName = "Journey";
	protected modelName = "journey";

	protected async validate(entity: JourneyAttributes): Promise<void> {
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}