// This file was generated by generate-services.ts
import { LoginHistory } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type LoginHistoryAttributes = Omit<LoginHistory, "id" | "createdAt" | "updatedAt">;

export class LoginHistoryRepository extends BaseRepository<LoginHistory> {
	protected model = prisma.loginHistory;
	protected entityName = "LoginHistory";
	protected modelName = "loginHistory";

	protected async validate(entity: LoginHistoryAttributes): Promise<void> {
		if (entity.success === undefined || entity.success === null) throw new BadRequestError("success is required");
		if (!entity.timestamp) throw new BadRequestError("timestamp is required");
	}

}