// This file was generated by generate-services.ts
import type { LoginHistory } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type LoginHistoryAttributes = Omit<LoginHistory, "id" | "createdAt" | "updatedAt">;

export class LoginHistoryRepository extends BaseRepository<LoginHistory> {
  protected model = prisma.loginHistory;
  protected entityName = "LoginHistory";
  protected modelName = "loginHistory";

  protected async validate(entity: LoginHistoryAttributes): Promise<void> {
    if (entity.success === undefined || entity.success === null)
      throw new BadRequestError("success is required");
  }
}
