// This file was generated by generate-services.ts
import { MachineStatus } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type MachineStatusAttributes = Omit<MachineStatus, "id" | "createdAt" | "updatedAt">;

export class MachineStatusRepository extends BaseRepository<MachineStatus> {
	protected model = prisma.machineStatus;
	protected entityName = "MachineStatus";
	protected modelName = "machineStatus";

	protected async validate(entity: MachineStatusAttributes): Promise<void> {
		if (!entity.machineId) throw new BadRequestError("machineId is required");
		if (!entity.execution) throw new BadRequestError("execution is required");
		if (!entity.controller) throw new BadRequestError("controller is required");
		if (!entity.startTime) throw new BadRequestError("startTime is required");
	}

}