// This file was generated by generate-services.ts
import type { MicrosoftGraphToken } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type MicrosoftGraphTokenAttributes = Omit<MicrosoftGraphToken, "id" | "createdAt" | "updatedAt">;

export class MicrosoftGraphTokenRepository extends BaseRepository<MicrosoftGraphToken> {
  protected model = prisma.microsoftGraphToken;
  protected entityName = "MicrosoftGraphToken";
  protected modelName = "microsoftGraphToken";

  protected async validate(entity: MicrosoftGraphTokenAttributes): Promise<void> {
    if (!entity.employeeId)
      throw new BadRequestError("employeeId is required");
    if (!entity.accessToken)
      throw new BadRequestError("accessToken is required");
    if (!entity.refreshToken)
      throw new BadRequestError("refreshToken is required");
    if (!entity.tokenType)
      throw new BadRequestError("tokenType is required");
    if (!entity.scope)
      throw new BadRequestError("scope is required");
    if (!entity.expiresAt)
      throw new BadRequestError("expiresAt is required");
    if (!entity.lastRefreshedAt)
      throw new BadRequestError("lastRefreshedAt is required");
  }
}
