// This file was generated by generate-services.ts
import { Note } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type NoteAttributes = Omit<Note, "id" | "createdAt" | "updatedAt">;

export class NoteRepository extends BaseRepository<Note> {
	protected model = prisma.note;
	protected entityName = "Note";
	protected modelName = "note";

	protected async validate(entity: NoteAttributes): Promise<void> {
		if (!entity.entityId) throw new BadRequestError("entityId is required");
		if (!entity.entityType) throw new BadRequestError("entityType is required");
		if (!entity.type) throw new BadRequestError("type is required");
		if (!entity.body) throw new BadRequestError("body is required");
	}

}