// This file was generated by generate-services.ts
import type { OptionRuleTarget } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type OptionRuleTargetAttributes = Omit<OptionRuleTarget, "id" | "createdAt" | "updatedAt">;

export class OptionRuleTargetRepository extends BaseRepository<OptionRuleTarget> {
  protected model = prisma.optionRuleTarget;
  protected entityName = "OptionRuleTarget";
  protected modelName = "optionRuleTarget";

  protected async validate(entity: OptionRuleTargetAttributes): Promise<void> {
    if (!entity.ruleId)
      throw new BadRequestError("ruleId is required");
    if (!entity.optionId)
      throw new BadRequestError("optionId is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
