// This file was generated by generate-services.ts
import { PerformanceSheetVersion } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type PerformanceSheetVersionAttributes = Omit<PerformanceSheetVersion, "id" | "createdAt" | "updatedAt">;

export class PerformanceSheetVersionRepository extends BaseRepository<PerformanceSheetVersion> {
	protected model = prisma.performanceSheetVersion;
	protected entityName = "PerformanceSheetVersion";
	protected modelName = "performanceSheetVersion";

	protected async validate(entity: PerformanceSheetVersionAttributes): Promise<void> {
		if (!entity.sections) throw new BadRequestError("sections is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}