// This file was generated by generate-services.ts
import type { PerformanceSheet } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type PerformanceSheetAttributes = Omit<PerformanceSheet, "id" | "createdAt" | "updatedAt">;

export class PerformanceSheetRepository extends BaseRepository<PerformanceSheet> {
  protected model = prisma.performanceSheet;
  protected entityName = "PerformanceSheet";
  protected modelName = "performanceSheet";

  protected async validate(entity: PerformanceSheetAttributes): Promise<void> {
    if (!entity.versionId)
      throw new BadRequestError("versionId is required");
    if (!entity.data)
      throw new BadRequestError("data is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
