// This file was generated by generate-services.ts
import { PerformanceSheet } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type PerformanceSheetAttributes = Omit<PerformanceSheet, "id" | "createdAt" | "updatedAt">;

export class PerformanceSheetRepository extends BaseRepository<PerformanceSheet> {
	protected model = prisma.performanceSheet;
	protected entityName = "PerformanceSheet";
	protected modelName = "performanceSheet";

	protected async validate(entity: PerformanceSheetAttributes): Promise<void> {
		if (!entity.versionId) throw new BadRequestError("versionId is required");
		if (!entity.data) throw new BadRequestError("data is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}