// This file was generated by generate-services.ts
import { Permission } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type PermissionAttributes = Omit<Permission, "id" | "createdAt" | "updatedAt">;

export class PermissionRepository extends BaseRepository<Permission> {
	protected model = prisma.permission;
	protected entityName = "Permission";
	protected modelName = "permission";

	protected async validate(entity: PermissionAttributes): Promise<void> {
		if (!entity.resource) throw new BadRequestError("resource is required");
		if (!entity.action) throw new BadRequestError("action is required");
	}

}