// This file was generated by generate-services.ts
import { PermissionException } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type PermissionExceptionAttributes = Omit<PermissionException, "id" | "createdAt" | "updatedAt">;

export class PermissionExceptionRepository extends BaseRepository<PermissionException> {
	protected model = prisma.permissionException;
	protected entityName = "PermissionException";
	protected modelName = "permissionException";

	protected async validate(entity: PermissionExceptionAttributes): Promise<void> {
		if (!entity.userId) throw new BadRequestError("userId is required");
		if (!entity.permissionId) throw new BadRequestError("permissionId is required");
		if (!entity.scope) throw new BadRequestError("scope is required");
		if (!entity.scopeKey) throw new BadRequestError("scopeKey is required");
	}

}