// This file was generated by generate-services.ts
import type { PostalCode } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type PostalCodeAttributes = Omit<PostalCode, "id" | "createdAt" | "updatedAt">;

export class PostalCodeRepository extends BaseRepository<PostalCode> {
  protected model = prisma.postalCode;
  protected entityName = "PostalCode";
  protected modelName = "postalCode";

  protected async validate(entity: PostalCodeAttributes): Promise<void> {
    if (!entity.countryCode)
      throw new BadRequestError("countryCode is required");
    if (!entity.postalCode)
      throw new BadRequestError("postalCode is required");
    if (!entity.latitude)
      throw new BadRequestError("latitude is required");
    if (!entity.longitude)
      throw new BadRequestError("longitude is required");
  }
}
