// This file was generated by generate-services.ts
import { PostalCode } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type PostalCodeAttributes = Omit<PostalCode, "id" | "createdAt" | "updatedAt">;

export class PostalCodeRepository extends BaseRepository<PostalCode> {
	protected model = prisma.postalCode;
	protected entityName = "PostalCode";
	protected modelName = "postalCode";

	protected async validate(entity: PostalCodeAttributes): Promise<void> {
		if (!entity.countryCode) throw new BadRequestError("countryCode is required");
		if (!entity.postalCode) throw new BadRequestError("postalCode is required");
		if (!entity.latitude) throw new BadRequestError("latitude is required");
		if (!entity.longitude) throw new BadRequestError("longitude is required");
	}

}