// This file was generated by generate-services.ts
import { ProductClass } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type ProductClassAttributes = Omit<ProductClass, "id" | "createdAt" | "updatedAt">;

export class ProductClassRepository extends BaseRepository<ProductClass> {
	protected model = prisma.productClass;
	protected entityName = "ProductClass";
	protected modelName = "productClass";

	protected async validate(entity: ProductClassAttributes): Promise<void> {
		if (!entity.code) throw new BadRequestError("code is required");
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.depth) throw new BadRequestError("depth is required");
		if (entity.isActive === undefined || entity.isActive === null) throw new BadRequestError("isActive is required");
	}

}