// This file was generated by generate-services.ts
import { QuoteRevision } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type QuoteRevisionAttributes = Omit<QuoteRevision, "id" | "createdAt" | "updatedAt">;

export class QuoteRevisionRepository extends BaseRepository<QuoteRevision> {
	protected model = prisma.quoteRevision;
	protected entityName = "QuoteRevision";
	protected modelName = "quoteRevision";

	protected async validate(entity: QuoteRevisionAttributes): Promise<void> {
		if (!entity.quoteId) throw new BadRequestError("quoteId is required");
		if (!entity.revision) throw new BadRequestError("revision is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}

}