// This file was generated by generate-services.ts
import type { QuoteTerms } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type QuoteTermsAttributes = Omit<QuoteTerms, "id" | "createdAt" | "updatedAt">;

export class QuoteTermsRepository extends BaseRepository<QuoteTerms> {
  protected model = prisma.quoteTerms;
  protected entityName = "QuoteTerms";
  protected modelName = "quoteTerms";

  protected async validate(entity: QuoteTermsAttributes): Promise<void> {
    if (!entity.quoteRevisionId)
      throw new BadRequestError("quoteRevisionId is required");
    if (!entity.netDays)
      throw new BadRequestError("netDays is required");
  }
}
