// This file was generated by generate-services.ts
import { QuoteTerms } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type QuoteTermsAttributes = Omit<QuoteTerms, "id" | "createdAt" | "updatedAt">;

export class QuoteTermsRepository extends BaseRepository<QuoteTerms> {
	protected model = prisma.quoteTerms;
	protected entityName = "QuoteTerms";
	protected modelName = "quoteTerms";

	protected async validate(entity: QuoteTermsAttributes): Promise<void> {
		if (!entity.quoteRevisionId) throw new BadRequestError("quoteRevisionId is required");
		if (!entity.netDays) throw new BadRequestError("netDays is required");
	}

}