// This file was generated by generate-services.ts
import type { QuoteNote } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type QuoteNoteAttributes = Omit<QuoteNote, "id" | "createdAt" | "updatedAt">;

export class QuoteNoteRepository extends BaseRepository<QuoteNote> {
  protected model = prisma.quoteNote;
  protected entityName = "QuoteNote";
  protected modelName = "quoteNote";

  protected async validate(entity: QuoteNoteAttributes): Promise<void> {
    if (!entity.quoteRevisionId)
      throw new BadRequestError("quoteRevisionId is required");
    if (!entity.body)
      throw new BadRequestError("body is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
