// This file was generated by generate-services.ts
import type { RolePermission } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type RolePermissionAttributes = Omit<RolePermission, "id" | "createdAt" | "updatedAt">;

export class RolePermissionRepository extends BaseRepository<RolePermission> {
  protected model = prisma.rolePermission;
  protected entityName = "RolePermission";
  protected modelName = "rolePermission";

  protected async validate(entity: RolePermissionAttributes): Promise<void> {
    if (!entity.roleId)
      throw new BadRequestError("roleId is required");
    if (!entity.permissionId)
      throw new BadRequestError("permissionId is required");
  }
}
