// This file was generated by generate-services.ts
import { Role } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type RoleAttributes = Omit<Role, "id" | "createdAt" | "updatedAt">;

export class RoleRepository extends BaseRepository<Role> {
	protected model = prisma.role;
	protected entityName = "Role";
	protected modelName = "role";

	protected async validate(entity: RoleAttributes): Promise<void> {
		if (!entity.name) throw new BadRequestError("name is required");
		if (entity.isSystem === undefined || entity.isSystem === null) throw new BadRequestError("isSystem is required");
	}

}