// This file was generated by generate-services.ts
import { RolePermission } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type RolePermissionAttributes = Omit<RolePermission, "id" | "createdAt" | "updatedAt">;

export class RolePermissionRepository extends BaseRepository<RolePermission> {
	protected model = prisma.rolePermission;
	protected entityName = "RolePermission";
	protected modelName = "rolePermission";

	protected async validate(entity: RolePermissionAttributes): Promise<void> {
		if (!entity.roleId) throw new BadRequestError("roleId is required");
		if (!entity.permissionId) throw new BadRequestError("permissionId is required");
	}

}