// This file was generated by generate-services.ts
import type { ShiftNote } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type ShiftNoteAttributes = Omit<ShiftNote, "id" | "createdAt" | "updatedAt">;

export class ShiftNoteRepository extends BaseRepository<ShiftNote> {
  protected model = prisma.shiftNote;
  protected entityName = "ShiftNote";
  protected modelName = "shiftNote";

  protected async validate(entity: ShiftNoteAttributes): Promise<void> {
    if (!entity.empNum)
      throw new BadRequestError("empNum is required");
    if (!entity.hoursId)
      throw new BadRequestError("hoursId is required");
    if (!entity.shiftNote)
      throw new BadRequestError("shiftNote is required");
    if (!entity.dateEntered)
      throw new BadRequestError("dateEntered is required");
  }
}
