// This file was generated by generate-services.ts
import { Tag } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type TagAttributes = Omit<Tag, "id" | "createdAt" | "updatedAt">;

export class TagRepository extends BaseRepository<Tag> {
	protected model = prisma.tag;
	protected entityName = "Tag";
	protected modelName = "tag";

	protected async validate(entity: TagAttributes): Promise<void> {
		if (!entity.description) throw new BadRequestError("description is required");
		if (!entity.parentTable) throw new BadRequestError("parentTable is required");
		if (!entity.parentId) throw new BadRequestError("parentId is required");
		if (!entity.createdBy) throw new BadRequestError("createdBy is required");
	}

}