// This file was generated by generate-services.ts
import type { TeamsChatCache } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type TeamsChatCacheAttributes = Omit<TeamsChatCache, "id" | "createdAt" | "updatedAt">;

export class TeamsChatCacheRepository extends BaseRepository<TeamsChatCache> {
  protected model = prisma.teamsChatCache;
  protected entityName = "TeamsChatCache";
  protected modelName = "teamsChatCache";

  protected async validate(entity: TeamsChatCacheAttributes): Promise<void> {
    if (!entity.employeeId)
      throw new BadRequestError("employeeId is required");
    if (!entity.recipientUserId)
      throw new BadRequestError("recipientUserId is required");
    if (!entity.chatId)
      throw new BadRequestError("chatId is required");
    if (!entity.lastUsedAt)
      throw new BadRequestError("lastUsedAt is required");
  }
}
