// This file was generated by generate-services.ts
import { UserSettings } from "@prisma/client";
import { BaseRepository } from "./_base.repository";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type UserSettingsAttributes = Omit<UserSettings, "id" | "createdAt" | "updatedAt">;

export class UserSettingsRepository extends BaseRepository<UserSettings> {
	protected model = prisma.userSettings;
	protected entityName = "UserSettings";
	protected modelName = "userSettings";

	protected async validate(entity: UserSettingsAttributes): Promise<void> {
		if (!entity.userId) throw new BadRequestError("userId is required");
		if (!entity.settings) throw new BadRequestError("settings is required");
	}

}