// This file was generated by generate-services.ts
import type { UserSettings } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseRepository } from "./_base.repository";

type UserSettingsAttributes = Omit<UserSettings, "id" | "createdAt" | "updatedAt">;

export class UserSettingsRepository extends BaseRepository<UserSettings> {
  protected model = prisma.userSettings;
  protected entityName = "UserSettings";
  protected modelName = "userSettings";

  protected async validate(entity: UserSettingsAttributes): Promise<void> {
    if (!entity.userId)
      throw new BadRequestError("userId is required");
  }
}
