import { mapBackendToFrontend, MappingConfig } from './universal-mapping';

export const RFQ_MAPPING: MappingConfig = {
  reference: 'referenceNumber',
  date: 'date',
  customer: 'customer',
  street_address: 'streetAddress',
  city: 'city',
  state_province: 'state',
  zip_code: { key: 'zip', transform: (v) => v !== undefined && v !== null ? String(v) : '' },
  country: 'country',
  contact_name: 'contactName',
  contact_position: 'position',
  contact_phone_number: 'phone',
  contact_email: 'email',
  dealer_name: 'dealerName',
  dealer_salesman: 'dealerSalesman',
  days_per_week_running: { key: 'daysPerWeek', transform: (v) => v !== undefined && v !== null ? String(v) : '' },
  shifts_per_day: { key: 'shiftsPerDay', transform: (v) => v !== undefined && v !== null ? String(v) : '' },
  line_application: 'lineApplication',
  type_of_line: 'typeOfLine',
  pull_thru: { key: 'pullThrough', transform: (v) => v ? 'Yes' : 'No' },
  coil_width_max: { key: 'coilWidthMax', transform: (v) => v !== undefined && v !== null ? String(v) : '' },
  coil_width_min: { key: 'coilWidthMin', transform: (v) => v !== undefined && v !== null ? String(v) : '' },
  max_coil_od: { key: 'maxCoilOD', transform: (v) => v !== undefined && v !== null ? String(v) : '' },
  coil_id: { key: 'coilID', transform: (v) => v !== undefined && v !== null ? String(v) : '' },
  coil_weight_max: { key: 'coilWeightMax', transform: (v) => v !== undefined && v !== null ? String(v) : '' },
  coil_handling_cap_max: { key: 'coilHandlingMax', transform: (v) => v !== undefined && v !== null ? String(v) : '' },
  // Add more direct or transformed fields as needed
};

export function mapBackendToFrontendRFQ(backendData: any) {
  return mapBackendToFrontend(backendData, RFQ_MAPPING, (backend, _partial) => ({
    maxThick: {
      materialThickness: backend.max_material_thickness !== undefined && backend.max_material_thickness !== null ? String(backend.max_material_thickness) : '',
      coilWidth: backend.max_material_width !== undefined && backend.max_material_width !== null ? String(backend.max_material_width) : '',
      materialType: backend.max_material_type || '',
      yieldStrength: backend.max_yield_strength !== undefined && backend.max_yield_strength !== null ? String(backend.max_yield_strength) : '',
      materialTensile: backend.max_tensile_strength !== undefined && backend.max_tensile_strength !== null ? String(backend.max_tensile_strength) : '',
      coilWeight: backend.max_coil_weight !== undefined && backend.max_coil_weight !== null ? String(backend.max_coil_weight) : '',
      maxFPM: backend.max_fpm !== undefined && backend.max_fpm !== null ? String(backend.max_fpm) : '',
      coilOD: backend.max_coil_od !== undefined && backend.max_coil_od !== null ? String(backend.max_coil_od) : '',
      coilID: backend.max_coil_id !== undefined && backend.max_coil_id !== null ? String(backend.max_coil_id) : (backend.coil_id !== undefined && backend.coil_id !== null ? String(backend.coil_id) : ''),
    },
    atFull: {
      materialThickness: backend.full_material_thickness !== undefined && backend.full_material_thickness !== null ? String(backend.full_material_thickness) : '',
      coilWidth: backend.full_material_width !== undefined && backend.full_material_width !== null ? String(backend.full_material_width) : '',
      materialType: backend.full_material_type || '',
      yieldStrength: backend.full_yield_strength !== undefined && backend.full_yield_strength !== null ? String(backend.full_yield_strength) : '',
      materialTensile: backend.full_tensile_strength !== undefined && backend.full_tensile_strength !== null ? String(backend.full_tensile_strength) : '',
      coilWeight: backend.full_coil_weight !== undefined && backend.full_coil_weight !== null ? String(backend.full_coil_weight) : '',
      maxFPM: backend.full_fpm !== undefined && backend.full_fpm !== null ? String(backend.full_fpm) : '',
      coilOD: backend.full_coil_od !== undefined && backend.full_coil_od !== null ? String(backend.full_coil_od) : '',
      coilID: backend.full_coil_id !== undefined && backend.full_coil_id !== null ? String(backend.full_coil_id) : (backend.coil_id !== undefined && backend.coil_id !== null ? String(backend.coil_id) : ''),
    },
    minThick: {
      materialThickness: backend.min_material_thickness !== undefined && backend.min_material_thickness !== null ? String(backend.min_material_thickness) : '',
      coilWidth: backend.min_material_width !== undefined && backend.min_material_width !== null ? String(backend.min_material_width) : '',
      materialType: backend.min_material_type || '',
      yieldStrength: backend.min_yield_strength !== undefined && backend.min_yield_strength !== null ? String(backend.min_yield_strength) : '',
      materialTensile: backend.min_tensile_strength !== undefined && backend.min_tensile_strength !== null ? String(backend.min_tensile_strength) : '',
      coilWeight: backend.min_coil_weight !== undefined && backend.min_coil_weight !== null ? String(backend.min_coil_weight) : '',
      maxFPM: backend.min_fpm !== undefined && backend.min_fpm !== null ? String(backend.min_fpm) : '',
      coilOD: backend.min_coil_od !== undefined && backend.min_coil_od !== null ? String(backend.min_coil_od) : '',
      coilID: backend.min_coil_id !== undefined && backend.min_coil_id !== null ? String(backend.min_coil_id) : (backend.coil_id !== undefined && backend.coil_id !== null ? String(backend.coil_id) : ''),
    },
    atWidth: {
      materialThickness: backend.width_material_thickness !== undefined && backend.width_material_thickness !== null ? String(backend.width_material_thickness) : '',
      coilWidth: backend.width_material_width !== undefined && backend.width_material_width !== null ? String(backend.width_material_width) : '',
      materialType: backend.width_material_type || '',
      yieldStrength: backend.width_yield_strength !== undefined && backend.width_yield_strength !== null ? String(backend.width_yield_strength) : '',
      materialTensile: backend.width_tensile_strength !== undefined && backend.width_tensile_strength !== null ? String(backend.width_tensile_strength) : '',
      coilWeight: backend.width_coil_weight !== undefined && backend.width_coil_weight !== null ? String(backend.width_coil_weight) : '',
      maxFPM: backend.width_fpm !== undefined && backend.width_fpm !== null ? String(backend.width_fpm) : '',
      coilOD: backend.width_coil_od !== undefined && backend.width_coil_od !== null ? String(backend.width_coil_od) : '',
      coilID: backend.width_coil_id !== undefined && backend.width_coil_id !== null ? String(backend.width_coil_id) : (backend.coil_id !== undefined && backend.coil_id !== null ? String(backend.coil_id) : ''),
    },
    // Add more nested/complex fields as needed
  }));
} 