import {
  ComparisonOperator,
  Configuration,
  ConfigurationStatus,
  Option,
  OptionCategory,
  ProductClass,
  Rule,
  RuleAction,
} from "./types";

export const sampleCustomers = [
  {
    id: 1,
    name: "Acme Corporation",
    contact: "John Smith",
    email: "john@acmecorp.com",
    phone: "(555) 123-4567",
    status: "active",
    type: "Enterprise",
    location: "New York, NY",
    lastQuote: "2025-03-28",
    totalValue: 125000,
  },
  {
    id: 2,
    name: "Globex Industries",
    contact: "Jane Doe",
    email: "jane@globex.com",
    phone: "(555) 987-6543",
    status: "pending",
    type: "Mid-Market",
    location: "Chicago, IL",
    lastQuote: "2025-04-01",
    totalValue: 67500,
  },
  {
    id: 3,
    name: "Stark Enterprises",
    contact: "Tony Stark",
    email: "tony@stark.com",
    phone: "(555) 111-2222",
    status: "active",
    type: "Enterprise",
    location: "Los Angeles, CA",
    lastQuote: "2025-03-15",
    totalValue: 437000,
  },
  {
    id: 4,
    name: "Umbrella Corp",
    contact: "Albert Wesker",
    email: "wesker@umbrella.com",
    phone: "(555) 333-4444",
    status: "inactive",
    type: "Enterprise",
    location: "Seattle, WA",
    lastQuote: "2025-02-12",
    totalValue: 285000,
  },
  {
    id: 5,
    name: "Small Business LLC",
    contact: "Sarah Connor",
    email: "sarah@smallbiz.com",
    phone: "(555) 555-5555",
    status: "active",
    type: "Small Business",
    location: "Austin, TX",
    lastQuote: "2025-04-05",
    totalValue: 28500,
  },
  {
    id: 6,
    name: "Tech Solutions Inc",
    contact: "Peter Parker",
    email: "peter@techsolutions.com",
    phone: "(555) 777-8888",
    status: "pending",
    type: "Mid-Market",
    location: "Boston, MA",
    lastQuote: "2025-04-08",
    totalValue: 87000,
  },
  {
    id: 7,
    name: "Global Dynamics",
    contact: "Nathan Stark",
    email: "nathan@globaldynamics.com",
    phone: "(555) 999-0000",
    status: "active",
    type: "Enterprise",
    location: "Portland, OR",
    lastQuote: "2025-03-22",
    totalValue: 195000,
  },
];

export const sampleCustomer = {
  id: 3,
  name: "Stark Enterprises",
  logo: "/api/placeholder/48/48",
  type: "Enterprise",
  status: "active",
  industry: "Technology & Manufacturing",
  website: "www.starkenterprises.com",
  createdAt: "2023-11-15",
  primaryContact: {
    name: "Tony Stark",
    role: "CEO",
    email: "tony@stark.com",
    phone: "(555) 111-2222",
    profileImage: "/api/placeholder/40/40",
  },
  addresses: [
    {
      type: "Billing",
      street: "10880 Malibu Point",
      city: "Malibu",
      state: "CA",
      zip: "90265",
      country: "USA",
      isPrimary: true,
    },
    {
      type: "Shipping",
      street: "200 Park Avenue",
      city: "New York",
      state: "NY",
      zip: "10166",
      country: "USA",
      isPrimary: false,
    },
  ],
  additionalContacts: [
    {
      name: "Pepper Potts",
      role: "COO",
      email: "pepper@stark.com",
      phone: "(555) 111-3333",
      profileImage: "/api/placeholder/40/40",
    },
    {
      name: "Happy Hogan",
      role: "Security Director",
      email: "happy@stark.com",
      phone: "(555) 111-4444",
      profileImage: "/api/placeholder/40/40",
    },
  ],
  quotes: [
    {
      id: "Q-2025-042",
      date: "2025-03-15",
      status: "Accepted",
      amount: 437000,
      items: 7,
    },
    {
      id: "Q-2025-012",
      date: "2025-01-22",
      status: "Accepted",
      amount: 215000,
      items: 3,
    },
    {
      id: "Q-2024-089",
      date: "2024-11-05",
      status: "Expired",
      amount: 320000,
      items: 5,
    },
  ],
  orders: [
    {
      id: "ORD-2025-037",
      date: "2025-03-18",
      status: "In Progress",
      amount: 437000,
      items: 7,
    },
    {
      id: "ORD-2025-008",
      date: "2025-01-30",
      status: "Completed",
      amount: 215000,
      items: 3,
    },
  ],
  notes: [
    {
      id: 1,
      author: "Jane Foster",
      date: "2025-04-10",
      content:
        "Tony mentioned they're planning to expand their renewable energy division in Q3. Potential opportunity for our new product line.",
      profileImage: "/api/placeholder/32/32",
    },
    {
      id: 2,
      author: "Steve Rogers",
      date: "2025-03-20",
      content:
        "Met with Tony and Pepper to discuss the last order delivery. They were very satisfied with the quick turnaround.",
      profileImage: "/api/placeholder/32/32",
    },
  ],
  activities: [
    {
      id: 1,
      type: "email",
      user: "Jane Foster",
      date: "2025-04-12",
      description: "Sent follow-up email about renewable energy products",
      profileImage: "/api/placeholder/32/32",
    },
    {
      id: 2,
      type: "meeting",
      user: "Steve Rogers",
      date: "2025-04-05",
      description: "Virtual meeting to discuss upcoming projects",
      profileImage: "/api/placeholder/32/32",
    },
    {
      id: 3,
      type: "quote",
      user: "Natasha Romanoff",
      date: "2025-03-14",
      description: "Created quote Q-2025-042",
      profileImage: "/api/placeholder/32/32",
    },
    {
      id: 4,
      type: "note",
      user: "Jane Foster",
      date: "2025-03-10",
      description: "Added note about expansion plans",
      profileImage: "/api/placeholder/32/32",
    },
  ],
  files: [
    {
      id: 1,
      name: "stark_enterprises_requirements.pdf",
      type: "PDF",
      size: "2.4 MB",
      uploadedBy: "Jane Foster",
      date: "2025-04-01",
    },
    {
      id: 2,
      name: "contract_2025.docx",
      type: "DOCX",
      size: "1.8 MB",
      uploadedBy: "Steve Rogers",
      date: "2025-03-20",
    },
  ],
};

export const sampleQuotes = [
  {
    id: "Q-2025-042",
    name: "Enterprise Solution Package",
    customer: "Stark Enterprises",
    contact: "Tony Stark",
    amount: 437000,
    date: "2025-03-15",
    expiry: "2025-04-14",
    status: "accepted",
    assignedTo: "Natasha Romanoff",
    items: 7,
  },
  {
    id: "Q-2025-041",
    name: "Annual Security Subscription",
    customer: "Wayne Enterprises",
    contact: "Bruce Wayne",
    amount: 320000,
    date: "2025-03-12",
    expiry: "2025-04-11",
    status: "pending",
    assignedTo: "Steve Rogers",
    items: 4,
  },
  {
    id: "Q-2025-039",
    name: "Custom Integration Services",
    customer: "Oscorp Industries",
    contact: "Norman Osborn",
    amount: 175000,
    date: "2025-03-10",
    expiry: "2025-04-09",
    status: "pending",
    assignedTo: "Jane Foster",
    items: 6,
  },
  {
    id: "Q-2025-037",
    name: "Basic Solution Package",
    customer: "Small Business LLC",
    contact: "Sarah Connor",
    amount: 28500,
    date: "2025-03-08",
    expiry: "2025-04-07",
    status: "expired",
    assignedTo: "Clint Barton",
    items: 3,
  },
  {
    id: "Q-2025-036",
    name: "Premium Support Contract",
    customer: "Global Dynamics",
    contact: "Nathan Stark",
    amount: 195000,
    date: "2025-03-07",
    expiry: "2025-04-06",
    status: "accepted",
    assignedTo: "Natasha Romanoff",
    items: 1,
  },
  {
    id: "Q-2025-034",
    name: "AI Integration Package",
    customer: "Cyberdyne Systems",
    contact: "Miles Dyson",
    amount: 650000,
    date: "2025-03-05",
    expiry: "2025-04-04",
    status: "draft",
    assignedTo: "Bruce Banner",
    items: 8,
  },
  {
    id: "Q-2025-031",
    name: "Research Tools Bundle",
    customer: "LexCorp",
    contact: "Lex Luthor",
    amount: 780000,
    date: "2025-03-02",
    expiry: "2025-04-01",
    status: "rejected",
    assignedTo: "Jane Foster",
    items: 12,
  },
  {
    id: "Q-2025-029",
    name: "Enterprise License Renewal",
    customer: "Hooli",
    contact: "Gavin Belson",
    amount: 550000,
    date: "2025-02-28",
    expiry: "2025-03-30",
    status: "accepted",
    assignedTo: "Steve Rogers",
    items: 5,
  },
  {
    id: "Q-2025-027",
    name: "Hardware & Software Package",
    customer: "Pied Piper",
    contact: "Richard Hendricks",
    amount: 120000,
    date: "2025-02-26",
    expiry: "2025-03-28",
    status: "pending",
    assignedTo: "Bruce Banner",
    items: 9,
  },
];

export const sampleQuote = {
  id: "Q-2025-042",
  name: "Enterprise Solution Package",
  description:
    "Complete enterprise solution with annual support and maintenance",
  customer: {
    id: "C-1001",
    name: "Stark Enterprises",
    contact: "Tony Stark",
    email: "tony@stark.com",
    phone: "(555) 111-2222",
    address: "10880 Malibu Point, Malibu, CA 90265",
  },
  date: "2025-03-15",
  expiry: "2025-04-14",
  validFor: "30 days",
  status: "accepted",
  acceptedDate: "2025-03-20",
  amount: 437000,
  tax: 34960,
  totalAmount: 471960,
  currency: "USD",
  discount: {
    type: "percentage",
    value: 10,
    amount: 48700,
  },
  assignedTo: "Natasha Romanoff",
  terms: "Net 30",
  paymentTerms:
    "Payment due within 30 days of invoice date. Accept credit card, ACH transfer, or check.",
  notes:
    "Client requested expedited implementation timeline. Premium support package included for first year.",
  items: [
    {
      id: 1,
      name: "Enterprise Core Platform",
      description: "Core platform license for up to 500 users",
      quantity: 1,
      unitPrice: 250000,
      discount: 25000,
      tax: 18000,
      total: 243000,
    },
    {
      id: 2,
      name: "Advanced Analytics Module",
      description: "Business intelligence and advanced reporting capabilities",
      quantity: 1,
      unitPrice: 75000,
      discount: 7500,
      tax: 5400,
      total: 72900,
    },
    {
      id: 3,
      name: "Premium Support Package",
      description: "24/7 priority support with 2-hour response time",
      quantity: 1,
      unitPrice: 50000,
      discount: 5000,
      tax: 3600,
      total: 48600,
    },
    {
      id: 4,
      name: "Implementation Services",
      description: "Full implementation including data migration and training",
      quantity: 80,
      unitPrice: 1500,
      discount: 12000,
      tax: 8640,
      total: 116640,
    },
    {
      id: 5,
      name: "Custom Integration",
      description: "Integration with existing ERP system",
      quantity: 40,
      unitPrice: 1200,
      discount: 4800,
      tax: 3456,
      total: 46656,
    },
  ],
  history: [
    {
      id: 1,
      date: "2025-03-20",
      user: "Tony Stark",
      action: "accepted",
      note: "Quote accepted via email",
    },
    {
      id: 2,
      date: "2025-03-18",
      user: "Natasha Romanoff",
      action: "sent",
      note: "Quote sent to client via email",
    },
    {
      id: 3,
      date: "2025-03-17",
      user: "Steve Rogers",
      action: "approved",
      note: "Quote approved by management",
    },
    {
      id: 4,
      date: "2025-03-16",
      user: "Natasha Romanoff",
      action: "submitted",
      note: "Quote submitted for approval",
    },
    {
      id: 5,
      date: "2025-03-15",
      user: "Natasha Romanoff",
      action: "created",
      note: "Quote created",
    },
  ],
  messages: [
    {
      id: 1,
      date: "2025-03-20",
      user: "Tony Stark",
      message: "Looks good. We're ready to proceed with this package.",
      direction: "incoming",
    },
    {
      id: 2,
      date: "2025-03-18",
      user: "Natasha Romanoff",
      message:
        "I've attached the quote for the Enterprise Solution Package we discussed. Please review and let me know if you have any questions.",
      direction: "outgoing",
    },
  ],
  approvals: [
    {
      id: 1,
      date: "2025-03-17",
      user: "Steve Rogers",
      status: "approved",
      note: "Pricing and terms look good.",
    },
  ],
};

export const sampleDeals = [
  {
    id: 1,
    name: "Acme Corp - Enterprise Solution",
    company: "Acme Corporation",
    contact: "John Smith",
    value: 125000,
    closeDate: "2025-05-15",
    probability: 70,
    stage: 3,
    priority: "high",
    activity: "2 days ago",
  },
  {
    id: 2,
    name: "Globex - Annual Subscription",
    company: "Globex Industries",
    contact: "Jane Doe",
    value: 67500,
    closeDate: "2025-06-01",
    probability: 50,
    stage: 2,
    priority: "medium",
    activity: "4 days ago",
  },
  {
    id: 3,
    name: "Stark Enterprises - New Product Line",
    company: "Stark Enterprises",
    contact: "Tony Stark",
    value: 437000,
    closeDate: "2025-04-30",
    probability: 90,
    stage: 4,
    priority: "high",
    activity: "Yesterday",
  },
  {
    id: 4,
    name: "Umbrella Corp - Security Package",
    company: "Umbrella Corp",
    contact: "Albert Wesker",
    value: 285000,
    closeDate: "2025-05-21",
    probability: 40,
    stage: 3,
    priority: "medium",
    activity: "1 week ago",
  },
  {
    id: 5,
    name: "Small Business LLC - Basic Solution",
    company: "Small Business LLC",
    contact: "Sarah Connor",
    value: 28500,
    closeDate: "2025-04-18",
    probability: 95,
    stage: 5,
    priority: "low",
    activity: "3 days ago",
  },
  {
    id: 6,
    name: "Tech Solutions - Premium Support",
    company: "Tech Solutions Inc",
    contact: "Peter Parker",
    value: 87000,
    closeDate: "2025-06-15",
    probability: 30,
    stage: 2,
    priority: "medium",
    activity: "Today",
  },
  {
    id: 7,
    name: "Global Dynamics - Custom Integration",
    company: "Global Dynamics",
    contact: "Nathan Stark",
    value: 195000,
    closeDate: "2025-05-30",
    probability: 60,
    stage: 1,
    priority: "high",
    activity: "1 day ago",
  },
  {
    id: 8,
    name: "Wayne Enterprises - Security Upgrade",
    company: "Wayne Enterprises",
    contact: "Bruce Wayne",
    value: 320000,
    closeDate: "2025-06-30",
    probability: 70,
    stage: 2,
    priority: "high",
    activity: "2 days ago",
  },
  {
    id: 9,
    name: "Daily Planet - Marketing Solution",
    company: "Daily Planet",
    contact: "Clark Kent",
    value: 45000,
    closeDate: "2025-04-25",
    probability: 90,
    stage: 5,
    priority: "medium",
    activity: "1 day ago",
  },
  {
    id: 10,
    name: "Cyberdyne Systems - AI Integration",
    company: "Cyberdyne Systems",
    contact: "Miles Dyson",
    value: 650000,
    closeDate: "2025-07-01",
    probability: 20,
    stage: 1,
    priority: "high",
    activity: "3 days ago",
  },
  {
    id: 11,
    name: "Oscorp - Research Tools",
    company: "Oscorp Industries",
    contact: "Norman Osborn",
    value: 175000,
    closeDate: "2025-05-15",
    probability: 45,
    stage: 3,
    priority: "medium",
    activity: "5 days ago",
  },
  {
    id: 12,
    name: "Pied Piper - Compression Algorithm",
    company: "Pied Piper",
    contact: "Richard Hendricks",
    value: 120000,
    closeDate: "2025-06-10",
    probability: 60,
    stage: 4,
    priority: "high",
    activity: "Today",
  },
  {
    id: 13,
    name: "Hooli - Enterprise License",
    company: "Hooli",
    contact: "Gavin Belson",
    value: 550000,
    closeDate: "2025-07-15",
    probability: 30,
    stage: 2,
    priority: "high",
    activity: "1 week ago",
  },
  {
    id: 14,
    name: "LexCorp - Infrastructure Upgrade",
    company: "LexCorp",
    contact: "Lex Luthor",
    value: 780000,
    closeDate: "2025-08-01",
    probability: 40,
    stage: 3,
    priority: "high",
    activity: "2 days ago",
  },
  {
    id: 15,
    name: "Dunder Mifflin - Paper Supply Chain",
    company: "Dunder Mifflin",
    contact: "Michael Scott",
    value: 42000,
    closeDate: "2025-04-20",
    probability: 95,
    stage: 6,
    priority: "low",
    activity: "3 weeks ago",
  },
];

// Catalog Service Entities
export const sampleProductClasses: ProductClass[] = [
  {
    id: "foo",
    name: "Foo",
    description: "Foo product line",
    parentId: null,
    depth: 0,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "foo-basic",
    name: "Foo Basic",
    description: "Basic variant of Foo",
    parentId: "foo",
    depth: 1,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "foo-basic-12",
    name: "Foo Basic 12",
    description: "Foo Basic 12-inch model",
    parentId: "foo-basic",
    depth: 2,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "foo-basic-24",
    name: "Foo Basic 24",
    description: "Foo Basic 24-inch model",
    parentId: "foo-basic",
    depth: 2,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "foo-supreme",
    name: "Foo Supreme",
    description: "Premium variant of Foo",
    parentId: "foo",
    depth: 1,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "foo-supreme-12",
    name: "Foo Supreme 12",
    description: "Foo Supreme 12-inch model",
    parentId: "foo-supreme",
    depth: 2,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "foo-supreme-24",
    name: "Foo Supreme 24",
    description: "Foo Supreme 24-inch model",
    parentId: "foo-supreme",
    depth: 2,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "bar",
    name: "Bar",
    description: "Bar product line",
    parentId: null,
    depth: 0,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "bar-basic",
    name: "Bar Basic",
    description: "Basic variant of Bar",
    parentId: "bar",
    depth: 1,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "bar-basic-12",
    name: "Bar Basic 12",
    description: "Bar Basic 12-inch model",
    parentId: "bar-basic",
    depth: 2,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "bar-basic-24",
    name: "Bar Basic 24",
    description: "Bar Basic 24-inch model",
    parentId: "bar-basic",
    depth: 2,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "bar-supreme",
    name: "Bar Supreme",
    description: "Premium variant of Bar",
    parentId: "bar",
    depth: 1,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "bar-supreme-12",
    name: "Bar Supreme 12",
    description: "Bar Supreme 12-inch model",
    parentId: "bar-supreme",
    depth: 2,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "bar-supreme-24",
    name: "Bar Supreme 24",
    description: "Bar Supreme 24-inch model",
    parentId: "bar-supreme",
    depth: 2,
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleOptionCategories: OptionCategory[] = [
  {
    id: "cat_roll_feed_assemblies",
    name: "Roll Feed Assemblies",
    description: "Roll Feed Assemblies",
    isRequired: true,
    allowMultiple: false,
    displayOrder: 1,
    productClassIds: ["foo", "bar"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_cabinets",
    name: "Cabinets",
    description: "Cabinets",
    isRequired: false,
    allowMultiple: false,
    displayOrder: 2,
    productClassIds: ["foo", "bar"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_passline_adjustment",
    name: "Passline Adjustment",
    description: "Passline Adjustment",
    isRequired: true,
    allowMultiple: false,
    displayOrder: 3,
    productClassIds: ["foo", "bar"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_additional_roll_feed",
    name: "Additional Roll Feed Options",
    description: "Additional Roll Feed Options",
    isRequired: false,
    allowMultiple: true,
    displayOrder: 4,
    productClassIds: ["foo", "bar"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_pull_thru_straighteners",
    name: "Pull Thru Straighteners",
    description: "Pull Thru Straighteners",
    isRequired: false,
    allowMultiple: false,
    displayOrder: 5,
    productClassIds: ["foo", "bar"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_foo_only",
    name: "Foo Only",
    description: "Foo Only",
    isRequired: false,
    allowMultiple: false,
    displayOrder: 6,
    productClassIds: ["foo"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_foo_supreme_only",
    name: "Foo Supreme Only",
    description: "Foo Supreme Only",
    isRequired: false,
    allowMultiple: false,
    displayOrder: 7,
    productClassIds: ["foo-supreme"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleOptions: Option[] = [
  {
    id: "opt_roll_feed_assembly_1",
    categoryId: "cat_roll_feed_assemblies",
    name: "Roll Feed Assembly 1",
    description: "Roll Feed Assembly 1",
    price: 100,
    displayOrder: 1,
    isStandard: true,
    allowQuantity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "opt_roll_feed_assembly_2",
    categoryId: "cat_roll_feed_assemblies",
    name: "Roll Feed Assembly 2",
    description: "Roll Feed Assembly 2",
    price: 200,
    displayOrder: 2,
    isStandard: false,
    allowQuantity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "opt_roll_feed_assembly_3",
    categoryId: "cat_roll_feed_assemblies",
    name: "Roll Feed Assembly 3",
    description: "Roll Feed Assembly 3",
    price: 300,
    displayOrder: 3,
    isStandard: false,
    allowQuantity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "opt_cabinet_1",
    categoryId: "cat_cabinets",
    name: "Cabinet 1",
    description: "Cabinet 1",
    price: 100,
    displayOrder: 1,
    isStandard: false,
    allowQuantity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "opt_cabinet_2",
    categoryId: "cat_cabinets",
    name: "Cabinet 2",
    description: "Cabinet 2",
    price: 200,
    displayOrder: 2,
    isStandard: false,
    allowQuantity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "opt_passline_adjustment_1",
    categoryId: "cat_passline_adjustment",
    name: "Passline Adjustment 1",
    description: "Passline Adjustment 1",
    price: 100,
    displayOrder: 1,
    isStandard: false,
    allowQuantity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "opt_passline_adjustment_2",
    categoryId: "cat_passline_adjustment",
    name: "Passline Adjustment 2",
    description: "Passline Adjustment 2",
    price: 200,
    displayOrder: 2,
    isStandard: false,
    allowQuantity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "opt_foo_only_1",
    categoryId: "cat_foo_only",
    name: "Foo Only 1",
    description: "Foo Only 1",
    price: 100,
    displayOrder: 1,
    isStandard: false,
    allowQuantity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "opt_foo_supreme_only_1",
    categoryId: "cat_foo_supreme_only",
    name: "Foo Supreme Only 1",
    description: "Foo Supreme Only 1",
    price: 100,
    displayOrder: 1,
    isStandard: false,
    allowQuantity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleOptionRules: Rule[] = [
  // Rule 1: Previously ENABLE Roll Feed Assembly 3 for Foo products
  // Converted to DISABLE for all non-Foo products (inverted logic)
  {
    id: "rule_foo_roll_feed",
    name: "Foo Roll Feed Assembly Rule",
    description: "Disable Roll Feed Assembly 3 for non-Foo products",
    active: true,
    priority: 10,
    targetOptionIds: ["opt_roll_feed_assembly_3"],
    action: RuleAction.DISABLE,
    condition: {
      type: "NOT",
      condition: {
        type: "SIMPLE",
        conditionType: "PRODUCT_CLASS",
        id: "foo",
      },
    },
    type: "OPTION",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Rule 2: Require Passline Adjustment 2 when Cabinet 2 is selected
  {
    id: "rule_cabinet_requires_passline",
    name: "Cabinet Requires Passline",
    description: "Selecting Cabinet 2 requires Passline Adjustment 2",
    active: true,
    priority: 20,
    targetOptionIds: ["opt_passline_adjustment_2"],
    action: RuleAction.REQUIRE,
    condition: {
      type: "SIMPLE",
      conditionType: "OPTION",
      id: "opt_cabinet_2",
    },
    type: "OPTION",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Rule 3: Previously complex ENABLE rule for Supreme 24-inch models
  // Convert to DISABLE for everything that doesn't match the condition
  {
    id: "rule_complex_condition",
    name: "Complex Supreme Rule",
    description:
      "Disable Cabinet 2 for non-Supreme 24-inch models or when Passline 1 is selected",
    active: true,
    priority: 30,
    targetOptionIds: ["opt_cabinet_2"],
    action: RuleAction.DISABLE,
    condition: {
      type: "NOT",
      condition: {
        type: "AND",
        conditions: [
          {
            type: "OR",
            conditions: [
              {
                type: "SIMPLE",
                conditionType: "PRODUCT_CLASS",
                id: "foo-supreme-24",
              },
              {
                type: "SIMPLE",
                conditionType: "PRODUCT_CLASS",
                id: "bar-supreme-24",
              },
            ],
          },
          {
            type: "NOT",
            condition: {
              type: "SIMPLE",
              conditionType: "OPTION",
              id: "opt_passline_adjustment_1",
            },
          },
        ],
      },
    },
    type: "OPTION",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Rule 4: Previously EXCLUDE rule - cannot select certain options together
  // Convert to DISABLE when the condition is true
  {
    id: "rule_assembly_exclusivity",
    name: "Roll Feed Assembly Exclusivity",
    description: "Disable Roll Feed Assembly 2 when Cabinet 1 is selected",
    active: true,
    priority: 15,
    targetOptionIds: ["opt_roll_feed_assembly_2"],
    action: RuleAction.DISABLE,
    condition: {
      type: "SIMPLE",
      conditionType: "OPTION",
      id: "opt_cabinet_1",
    },
    type: "OPTION",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Rule 5: Basic model constraint - already uses DISABLE, no change needed
  {
    id: "rule_basic_constraint",
    name: "Basic Model Option Constraint",
    description: "Basic models cannot use Roll Feed Assembly 3",
    active: true,
    priority: 25,
    targetOptionIds: ["opt_roll_feed_assembly_3"],
    action: RuleAction.DISABLE,
    condition: {
      type: "OR",
      conditions: [
        { type: "SIMPLE", conditionType: "PRODUCT_CLASS", id: "foo-basic" },
        { type: "SIMPLE", conditionType: "PRODUCT_CLASS", id: "bar-basic" },
      ],
    },
    type: "OPTION",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Rule 6: Multiple requirements - already uses REQUIRE, no change needed
  {
    id: "rule_multiple_requirements",
    name: "Multiple Option Selection",
    description:
      "Roll Feed Assembly 3 requires both Cabinet 2 and Passline Adjustment 2",
    active: true,
    priority: 35,
    targetOptionIds: ["opt_roll_feed_assembly_3"],
    action: RuleAction.REQUIRE,
    condition: {
      type: "AND",
      conditions: [
        { type: "SIMPLE", conditionType: "OPTION", id: "opt_cabinet_2" },
        {
          type: "SIMPLE",
          conditionType: "OPTION",
          id: "opt_passline_adjustment_2",
        },
      ],
    },
    type: "OPTION",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Rule 8: Previously HIDE premium options
  // Convert to DISABLE for the same condition
  {
    id: "rule_hide_premium_options",
    name: "Disable Premium Options",
    description: "Disable premium cabinet option for basic models",
    active: true,
    priority: 5,
    targetOptionIds: ["opt_cabinet_2"],
    action: RuleAction.DISABLE,
    condition: {
      type: "OR",
      conditions: [
        { type: "SIMPLE", conditionType: "PRODUCT_CLASS", id: "foo-basic" },
        { type: "SIMPLE", conditionType: "PRODUCT_CLASS", id: "bar-basic" },
      ],
    },
    type: "OPTION",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Rule 9: Complex nested logic
  {
    id: "rule_complex_nested",
    name: "Complex Nested Logic",
    description:
      "Disable passline adjustment if either (Supreme model AND Cabinet 1) OR Roll Feed Assembly 3",
    active: true,
    priority: 40,
    targetOptionIds: ["opt_passline_adjustment_1"],
    action: RuleAction.DISABLE,
    condition: {
      type: "OR",
      conditions: [
        {
          type: "AND",
          conditions: [
            {
              type: "OR",
              conditions: [
                {
                  type: "SIMPLE",
                  conditionType: "PRODUCT_CLASS",
                  id: "foo-supreme",
                },
                {
                  type: "SIMPLE",
                  conditionType: "PRODUCT_CLASS",
                  id: "bar-supreme",
                },
              ],
            },
            { type: "SIMPLE", conditionType: "OPTION", id: "opt_cabinet_1" },
          ],
        },
        {
          type: "SIMPLE",
          conditionType: "OPTION",
          id: "opt_roll_feed_assembly_3",
        },
      ],
    },
    type: "OPTION",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Rule 10: Previously ENABLE special Passline Adjustment for 24-inch models
  // Convert to DISABLE for everything that doesn't match the condition
  {
    id: "rule_24_inch_special",
    name: "24-inch Special Configuration",
    description: "Disable special Passline Adjustment for non-24-inch models",
    active: true,
    priority: 15,
    targetOptionIds: ["opt_passline_adjustment_2"],
    action: RuleAction.DISABLE,
    condition: {
      type: "NOT",
      condition: {
        type: "OR",
        conditions: [
          {
            type: "SIMPLE",
            conditionType: "PRODUCT_CLASS",
            id: "foo-supreme-24",
          },
          {
            type: "SIMPLE",
            conditionType: "PRODUCT_CLASS",
            id: "bar-supreme-24",
          },
        ],
      },
    },
    type: "OPTION",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleConfigurations: Configuration[] = [
  // Foo Basic 12 Configuration
  {
    id: "cfg-foo-basic-12-small",
    name: "Foo Basic 12 Small",
    description: "Foo Basic 12-inch with small format",
    productClassId: "foo-basic-12",
    options: [
      { optionId: "opt_roll_feed_assembly_1", quantity: 1 },
      { optionId: "opt_passline_adjustment_1", quantity: 1 },
    ],
    pricing: {
      basePrice: 1200,
      adjustments: 200, // Roll Feed Assembly 1 (100) + Passline Adjustment 1 (100)
      totalPrice: 1400,
    },
    status: ConfigurationStatus.PUBLISHED,
    isTemplate: true,
    createdBy: "system",
    createdAt: new Date("2024-01-15"),
    updatedBy: "system",
    updatedAt: new Date("2024-01-15"),
  },

  // Foo Supreme 24 Configuration
  {
    id: "cfg-foo-supreme-24",
    name: "Foo Supreme 24",
    description: "Foo Supreme 24-inch with premium options",
    productClassId: "foo-supreme-24",
    options: [
      { optionId: "opt_roll_feed_assembly_3", quantity: 1 },
      { optionId: "opt_cabinet_2", quantity: 1 },
      { optionId: "opt_passline_adjustment_2", quantity: 1 },
      { optionId: "opt_foo_supreme_only_1", quantity: 1 },
    ],
    pricing: {
      basePrice: 2400,
      adjustments: 800, // Roll Feed Assembly 3 (300) + Cabinet 2 (200) + Passline Adjustment 2 (200) + Foo Supreme Only 1 (100)
      totalPrice: 3200,
    },
    status: ConfigurationStatus.PUBLISHED,
    isTemplate: true,
    createdBy: "system",
    createdAt: new Date("2024-01-16"),
    updatedBy: "system",
    updatedAt: new Date("2024-01-16"),
  },

  // Bar Basic 12 Configuration
  {
    id: "cfg-bar-basic-12",
    name: "Bar Basic 12",
    description: "Basic Bar 12-inch model",
    productClassId: "bar-basic-12",
    options: [
      { optionId: "opt_roll_feed_assembly_1", quantity: 1 },
      { optionId: "opt_passline_adjustment_1", quantity: 1 },
    ],
    pricing: {
      basePrice: 1000,
      adjustments: 200, // Roll Feed Assembly 1 (100) + Passline Adjustment 1 (100)
      totalPrice: 1200,
    },
    status: ConfigurationStatus.PUBLISHED,
    isTemplate: true,
    createdBy: "system",
    createdAt: new Date("2024-01-17"),
    updatedBy: "system",
    updatedAt: new Date("2024-01-17"),
  },

  // Bar Supreme 24 Configuration
  {
    id: "cfg-bar-supreme-24",
    name: "Bar Supreme 24 Premium",
    description: "Premium Bar 24-inch with advanced options",
    productClassId: "bar-supreme-24",
    options: [
      { optionId: "opt_roll_feed_assembly_2", quantity: 1 },
      { optionId: "opt_cabinet_2", quantity: 1 },
      { optionId: "opt_passline_adjustment_2", quantity: 1 },
    ],
    pricing: {
      basePrice: 2000,
      adjustments: 600, // Roll Feed Assembly 2 (200) + Cabinet 2 (200) + Passline Adjustment 2 (200)
      totalPrice: 2600,
    },
    status: ConfigurationStatus.PUBLISHED,
    isTemplate: true,
    createdBy: "system",
    createdAt: new Date("2024-01-18"),
    updatedBy: "system",
    updatedAt: new Date("2024-01-18"),
  },

  // Custom Configuration (not a template)
  {
    id: "cfg-custom-foo-supreme",
    name: "Custom Foo Supreme",
    description: "Custom configuration based on Foo Supreme",
    productClassId: "foo-supreme-12",
    options: [
      { optionId: "opt_roll_feed_assembly_2", quantity: 1 },
      { optionId: "opt_cabinet_1", quantity: 1 },
      { optionId: "opt_passline_adjustment_2", quantity: 1 },
      { optionId: "opt_foo_supreme_only_1", quantity: 1 },
    ],
    pricing: {
      basePrice: 2100,
      adjustments: 600, // Roll Feed Assembly 2 (200) + Cabinet 1 (100) + Passline Adjustment 2 (200) + Foo Supreme Only 1 (100)
      totalPrice: 2700,
    },
    status: ConfigurationStatus.VALID,
    isTemplate: false,
    createdBy: "user123",
    createdAt: new Date("2024-02-10"),
    updatedBy: "user123",
    updatedAt: new Date("2024-02-10"),
  },

  // Draft Configuration
  {
    id: "cfg-draft-bar-custom",
    name: "Bar Custom Build",
    description: "Custom Bar configuration (in progress)",
    productClassId: "bar-basic-24",
    options: [
      { optionId: "opt_roll_feed_assembly_1", quantity: 1 },
      { optionId: "opt_passline_adjustment_1", quantity: 1 },
    ],
    pricing: {
      basePrice: 1200,
      adjustments: 200, // Roll Feed Assembly 1 (100) + Passline Adjustment 1 (100)
      totalPrice: 1400,
    },
    status: ConfigurationStatus.DRAFT,
    isTemplate: false,
    createdBy: "user456",
    createdAt: new Date("2024-03-05"),
    updatedBy: "user456",
    updatedAt: new Date("2024-03-05"),
  },
];

export const samplePerformanceRules: any[] = [
  {
    id: "perf_rule_1",
    name: "Rule 1",
    description: "Rule 1 description",
  },
];

export const sampleInputRules: Rule[] = [
  {
    id: "in_rule_1",
    name: "Temperature Range Rule",
    description: "Disable certain options when temperature is too high",
    active: true,
    priority: 1,
    targetOptionIds: ["option1", "option2"],
    action: RuleAction.DISABLE,
    condition: {
      type: "INPUT",
      fieldId: "temperature",
      operator: ComparisonOperator.GREATER_THAN,
      value: 100,
    },
    type: "INPUT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "in_rule_2",
    name: "Complex Rule",
    description: "Complex rule with multiple conditions",
    active: true,
    priority: 2,
    targetOptionIds: ["option1", "option2"],
    action: RuleAction.DISABLE,
    condition: {
      type: "AND",
      conditions: [
        {
          type: "INPUT",
          fieldId: "temperature",
          operator: ComparisonOperator.GREATER_THAN,
          value: 100,
        },
        {
          type: "SIMPLE",
          conditionType: "OPTION",
          id: "cooling-system",
          state: "SELECTED",
        },
      ],
    },
    type: "INPUT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
