// Auto-generated from Prisma schema
export enum FormFieldControlType {
  INPUT = "INPUT",
  TEXT_AREA = "TEXT_AREA",
  TEXTBOX = "TEXTBOX",
  DROPDOWN = "DROPDOWN",
  RADIO_BUTTON = "RADIO_BUTTON",
  MULTI_SELECT = "MULTI_SELECT",
  BUTTON_GROUP = "BUTTON_GROUP",
  GEO_LOCATION = "GEO_LOCATION",
  DATE_SELECTOR = "DATE_SELECTOR",
  TIME_SELECTOR = "TIME_SELECTOR",
  STAMP = "STAMP",
  SKETCH_PAD = "SKETCH_PAD",
  CAMERA = "CAMERA",
  SIGNATURE_PAD = "SIGNATURE_PAD",
}
