// This file was generated by generate-services.ts on 2025-08-14 10:09:19
import { Address } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type AddressAttributes = Omit<Address, "id" | "createdAt" | "updatedAt">;

export class AddressService extends BaseService<Address> {
	protected model = prisma.address;
	protected entityName = "Address";
	protected modelName = "address";

	protected async validate(entity: AddressAttributes): Promise<void> {
		if (!entity.companyId) throw new BadRequestError("companyId is required");
		if (!entity.addressLine1) throw new BadRequestError("addressLine1 is required");
		if (!entity.isPrimary) throw new BadRequestError("isPrimary is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}
}