// This file was generated by generate-services.ts on 2025-09-02 08:45:51
import { AuditLog } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type AuditLogAttributes = Omit<AuditLog, "id" | "createdAt" | "updatedAt">;

export class AuditLogService extends BaseService<AuditLog> {
	protected model = prisma.auditLog;
	protected entityName = "AuditLog";
	protected modelName = "auditLog";

	protected async validate(entity: AuditLogAttributes): Promise<void> {
		if (!entity.model) throw new BadRequestError("model is required");
		if (!entity.recordId) throw new BadRequestError("recordId is required");
		if (!entity.changedBy) throw new BadRequestError("changedBy is required");
		if (!entity.diff) throw new BadRequestError("diff is required");
	}
}