// This file was generated by generate-services.ts on 2025-07-22 08:36:53
import { AuditLog } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type AuditLogAttributes = Omit<AuditLog, "id" | "createdAt" | "updatedAt">;

export class AuditLogService extends BaseService<AuditLog> {
	protected model = prisma.auditLog;
	protected entityName = "AuditLog";
	protected modelName = "auditLog";

	protected async validate(entity: AuditLogAttributes): Promise<void> {
		if (!entity.entityType) throw new BadRequestError("entityType is required");
		if (!entity.entityId) throw new BadRequestError("entityId is required");
		if (!entity.action) throw new BadRequestError("action is required");
		if (!entity.oldData) throw new BadRequestError("oldData is required");
		if (!entity.newData) throw new BadRequestError("newData is required");
	}
}
