// This file was generated by generate-services.ts on 2025-08-26 10:53:59
import type { Chat } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type ChatAttributes = Omit<Chat, "id" | "createdAt" | "updatedAt">;

export class ChatService extends BaseService<Chat> {
  protected model = prisma.chat;
  protected entityName = "Chat";
  protected modelName = "chat";

  protected async validate(entity: ChatAttributes): Promise<void> {
    if (!entity.employeeId)
      throw new BadRequestError("employeeId is required");
    if (!entity.name)
      throw new BadRequestError("name is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
