// This file was generated by generate-services.ts on 2025-09-05 18:23:29
import type { CoilType } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type CoilTypeAttributes = Omit<CoilType, "id" | "createdAt" | "updatedAt">;

export class CoilTypeService extends BaseService<CoilType> {
  protected model = prisma.coilType;
  protected entityName = "CoilType";
  protected modelName = "coilType";

  protected async validate(entity: CoilTypeAttributes): Promise<void> {
    if (!entity.multiplier)
      throw new BadRequestError("multiplier is required");
    if (!entity.sortOrder)
      throw new BadRequestError("sortOrder is required");
    if (!entity.isArchived)
      throw new BadRequestError("isArchived is required");
  }
}
