// This file was generated by generate-services.ts on 2025-08-14 10:09:19
import { Company } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type CompanyAttributes = Omit<Company, "id" | "createdAt" | "updatedAt">;

export class CompanyService extends BaseService<Company> {
	protected model = prisma.company;
	protected entityName = "Company";
	protected modelName = "company";

	protected async validate(entity: CompanyAttributes): Promise<void> {
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.tags) throw new BadRequestError("tags is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}
}