// This file was generated by generate-services.ts on 2025-08-25 15:10:39
import type { Configuration } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type ConfigurationAttributes = Omit<Configuration, "id" | "createdAt" | "updatedAt">;

export class ConfigurationService extends BaseService<Configuration> {
  protected model = prisma.configuration;
  protected entityName = "Configuration";
  protected modelName = "configuration";

  protected async validate(entity: ConfigurationAttributes): Promise<void> {
    if (!entity.productClassId)
      throw new BadRequestError("productClassId is required");
    if (!entity.name)
      throw new BadRequestError("name is required");
    if (!entity.isTemplate)
      throw new BadRequestError("isTemplate is required");
    if (!entity.isActive)
      throw new BadRequestError("isActive is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
