// This file was generated by generate-services.ts on 2025-07-17 11:56:23
import { ConfigurationOption } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type ConfigurationOptionAttributes = Omit<ConfigurationOption, "id" | "createdAt" | "updatedAt">;

export class ConfigurationOptionService extends BaseService<ConfigurationOption> {
	protected model = prisma.configurationOption;
	protected entityName = "ConfigurationOption";
	protected modelName = "configurationOption";

	protected async validate(entity: ConfigurationOptionAttributes): Promise<void> {
		if (!entity.configurationId) throw new BadRequestError("configurationId is required");
		if (!entity.optionId) throw new BadRequestError("optionId is required");
	}
}
