// This file was generated by generate-services.ts on 2025-08-26 10:53:59
import type { ConfigurationOption } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type ConfigurationOptionAttributes = Omit<ConfigurationOption, "id" | "createdAt" | "updatedAt">;

export class ConfigurationOptionService extends BaseService<ConfigurationOption> {
  protected model = prisma.configurationOption;
  protected entityName = "ConfigurationOption";
  protected modelName = "configurationOption";

  protected async validate(entity: ConfigurationOptionAttributes): Promise<void> {
    if (!entity.configurationId)
      throw new BadRequestError("configurationId is required");
    if (!entity.optionId)
      throw new BadRequestError("optionId is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
