// This file was generated by generate-services.ts on 2025-08-14 10:09:19
import { Contact } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type ContactAttributes = Omit<Contact, "id" | "createdAt" | "updatedAt">;

export class ContactService extends BaseService<Contact> {
	protected model = prisma.contact;
	protected entityName = "Contact";
	protected modelName = "contact";

	protected async validate(entity: ContactAttributes): Promise<void> {
		if (!entity.companyId) throw new BadRequestError("companyId is required");
		if (!entity.firstName) throw new BadRequestError("firstName is required");
		if (!entity.isPrimary) throw new BadRequestError("isPrimary is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}
}