// This file was generated by generate-services.ts on 2025-08-26 14:00:06
import { Draft } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type DraftAttributes = Omit<Draft, "id" | "createdAt" | "updatedAt">;

export class DraftService extends BaseService<Draft> {
	protected model = prisma.draft;
	protected entityName = "Draft";
	protected modelName = "draft";

	protected async validate(entity: DraftAttributes): Promise<void> {
		if (!entity.entityType) throw new BadRequestError("entityType is required");
		if (!entity.data) throw new BadRequestError("data is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
	}
}