// This file was generated by generate-services.ts
import type { EmailLog } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type EmailLogAttributes = Omit<EmailLog, "id" | "createdAt" | "updatedAt">;

export class EmailLogService extends BaseService<EmailLog> {
  protected model = prisma.emailLog;
  protected entityName = "EmailLog";
  protected modelName = "emailLog";

  protected async validate(entity: EmailLogAttributes): Promise<void> {
    if (!entity.to)
      throw new BadRequestError("to is required");
    if (!entity.subject)
      throw new BadRequestError("subject is required");
  }
}
