// This file was generated by generate-services.ts on 2025-07-22 11:23:05
import { FieldsToWatch } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type FieldsToWatchAttributes = Omit<FieldsToWatch, "id" | "createdAt" | "updatedAt">;

export class FieldsToWatchService extends BaseService<FieldsToWatch> {
	protected model = prisma.fieldsToWatch;
	protected entityName = "FieldsToWatch";
	protected modelName = "fieldsToWatch";

	protected async validate(entity: FieldsToWatchAttributes): Promise<void> {
		if (!entity.entityType) throw new BadRequestError("entityType is required");
		if (!entity.fields) throw new BadRequestError("fields is required");
	}
}
