// This file was generated by generate-services.ts
import type { FormSubmission } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type FormSubmissionAttributes = Omit<FormSubmission, "id" | "createdAt" | "updatedAt">;

export class FormSubmissionService extends BaseService<FormSubmission> {
  protected model = prisma.formSubmission;
  protected entityName = "FormSubmission";
  protected modelName = "formSubmission";

  protected async validate(entity: FormSubmissionAttributes): Promise<void> {
    if (!entity.formId)
      throw new BadRequestError("formId is required");
    if (!entity.status)
      throw new BadRequestError("status is required");
  }
}
