// This file was generated by generate-services.ts
import type { FormPage } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type FormPageAttributes = Omit<FormPage, "id" | "createdAt" | "updatedAt">;

export class FormPageService extends BaseService<FormPage> {
  protected model = prisma.formPage;
  protected entityName = "FormPage";
  protected modelName = "formPage";

  protected async validate(entity: FormPageAttributes): Promise<void> {
    if (!entity.formId)
      throw new BadRequestError("formId is required");
    if (!entity.title)
      throw new BadRequestError("title is required");
    if (!entity.sequence)
      throw new BadRequestError("sequence is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
