// This file was generated by generate-services.ts
import type { FormSection } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type FormSectionAttributes = Omit<FormSection, "id" | "createdAt" | "updatedAt">;

export class FormSectionService extends BaseService<FormSection> {
  protected model = prisma.formSection;
  protected entityName = "FormSection";
  protected modelName = "formSection";

  protected async validate(entity: FormSectionAttributes): Promise<void> {
    if (!entity.formId)
      throw new BadRequestError("formId is required");
    if (!entity.title)
      throw new BadRequestError("title is required");
    if (!entity.orderIndex)
      throw new BadRequestError("orderIndex is required");
  }
}
