// This file was generated by generate-services.ts
import type { Invitation } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type InvitationAttributes = Omit<Invitation, "id" | "createdAt" | "updatedAt">;

export class InvitationService extends BaseService<Invitation> {
  protected model = prisma.invitation;
  protected entityName = "Invitation";
  protected modelName = "invitation";

  protected async validate(entity: InvitationAttributes): Promise<void> {
    if (!entity.token)
      throw new BadRequestError("token is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
