// This file was generated by generate-services.ts on 2025-09-05 18:23:29
import type { Item } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type ItemAttributes = Omit<Item, "id" | "createdAt" | "updatedAt">;

export class ItemService extends BaseService<Item> {
  protected model = prisma.item;
  protected entityName = "Item";
  protected modelName = "item";

  protected async validate(entity: ItemAttributes): Promise<void> {
    if (!entity.specifications)
      throw new BadRequestError("specifications is required");
    if (!entity.unitPrice)
      throw new BadRequestError("unitPrice is required");
    if (!entity.isActive)
      throw new BadRequestError("isActive is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
