// This file was generated by generate-services.ts on 2025-07-22 10:23:15
import { JourneyInteraction } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type JourneyInteractionAttributes = Omit<JourneyInteraction, "id" | "createdAt" | "updatedAt">;

export class JourneyInteractionService extends BaseService<JourneyInteraction> {
	protected model = prisma.journeyInteraction;
	protected entityName = "JourneyInteraction";
	protected modelName = "journeyInteraction";

	protected async validate(entity: JourneyInteractionAttributes): Promise<void> {
		if (!entity.journeyId) throw new BadRequestError("journeyId is required");
	}
}
