// This file was generated by generate-services.ts on 2025-08-25 15:13:33
import type { JourneyInteraction } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type JourneyInteractionAttributes = Omit<JourneyInteraction, "id" | "createdAt" | "updatedAt">;

export class JourneyInteractionService extends BaseService<JourneyInteraction> {
  protected model = prisma.journeyInteraction;
  protected entityName = "JourneyInteraction";
  protected modelName = "journeyInteraction";

  protected async validate(entity: JourneyInteractionAttributes): Promise<void> {
    if (!entity.journeyId)
      throw new BadRequestError("journeyId is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
