// This file was generated by generate-services.ts on 2025-09-05 18:23:29
import type { Journey } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type JourneyAttributes = Omit<Journey, "id" | "createdAt" | "updatedAt">;

export class JourneyService extends BaseService<Journey> {
  protected model = prisma.journey;
  protected entityName = "Journey";
  protected modelName = "journey";

  protected async validate(entity: JourneyAttributes): Promise<void> {
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
