// This file was generated by generate-services.ts on 2025-09-04 11:33:35
import { Journey } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type JourneyAttributes = Omit<Journey, "id" | "createdAt" | "updatedAt">;

export class JourneyService extends BaseService<Journey> {
	protected model = prisma.journey;
	protected entityName = "Journey";
	protected modelName = "journey";

	protected async validate(entity: JourneyAttributes): Promise<void> {
		if (!entity.createdById) throw new BadRequestError("createdById is required");
	}
}
