// This file was generated by generate-services.ts on 2025-09-05 18:23:29
import type { Machine } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type MachineAttributes = Omit<Machine, "id" | "createdAt" | "updatedAt">;

export class MachineService extends BaseService<Machine> {
  protected model = prisma.machine;
  protected entityName = "Machine";
  protected modelName = "machine";

  protected async validate(entity: MachineAttributes): Promise<void> {
    if (!entity.slug)
      throw new BadRequestError("slug is required");
    if (!entity.name)
      throw new BadRequestError("name is required");
    if (!entity.enabled)
      throw new BadRequestError("enabled is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
