// This file was generated by generate-services.ts on 2025-09-02 08:45:51
import { Machine } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type MachineAttributes = Omit<Machine, "id" | "createdAt" | "updatedAt">;

export class MachineService extends BaseService<Machine> {
	protected model = prisma.machine;
	protected entityName = "Machine";
	protected modelName = "machine";

	protected async validate(entity: MachineAttributes): Promise<void> {
		if (!entity.slug) throw new BadRequestError("slug is required");
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.enabled) throw new BadRequestError("enabled is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}
}