// This file was generated by generate-services.ts on 2025-08-26 10:53:59
import type { MachineStatus } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type MachineStatusAttributes = Omit<MachineStatus, "id" | "createdAt" | "updatedAt">;

export class MachineStatusService extends BaseService<MachineStatus> {
  protected model = prisma.machineStatus;
  protected entityName = "MachineStatus";
  protected modelName = "machineStatus";

  protected async validate(entity: MachineStatusAttributes): Promise<void> {
    if (!entity.machineId)
      throw new BadRequestError("machineId is required");
    if (!entity.execution)
      throw new BadRequestError("execution is required");
    if (!entity.controller)
      throw new BadRequestError("controller is required");
    if (!entity.startTime)
      throw new BadRequestError("startTime is required");
  }
}
