// This file was generated by generate-services.ts on 2025-08-26 14:00:06
import { Message } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type MessageAttributes = Omit<Message, "id" | "createdAt" | "updatedAt">;

export class MessageService extends BaseService<Message> {
	protected model = prisma.message;
	protected entityName = "Message";
	protected modelName = "message";

	protected async validate(entity: MessageAttributes): Promise<void> {
		if (!entity.chatId) throw new BadRequestError("chatId is required");
		if (!entity.role) throw new BadRequestError("role is required");
		if (!entity.content) throw new BadRequestError("content is required");
	}
}