// This file was generated by generate-services.ts on 2025-09-02 08:45:51
import type { Model } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type ModelAttributes = Omit<Model, "id" | "createdAt" | "updatedAt">;

export class ModelService extends BaseService<Model> {
  protected model = prisma.model;
  protected entityName = "Model";
  protected modelName = "model";

  protected async validate(entity: ModelAttributes): Promise<void> {
    if (!entity.model)
      throw new BadRequestError("model is required");
    if (!entity.data)
      throw new BadRequestError("data is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
