// This file was generated by generate-services.ts on 2025-08-25 15:13:33
import type { OptionHeader } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type OptionHeaderAttributes = Omit<OptionHeader, "id" | "createdAt" | "updatedAt">;

export class OptionHeaderService extends BaseService<OptionHeader> {
  protected model = prisma.optionHeader;
  protected entityName = "OptionHeader";
  protected modelName = "optionHeader";

  protected async validate(entity: OptionHeaderAttributes): Promise<void> {
    if (!entity.categoryId)
      throw new BadRequestError("categoryId is required");
    if (!entity.name)
      throw new BadRequestError("name is required");
    if (!entity.code)
      throw new BadRequestError("code is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
