// This file was generated by generate-services.ts on 2025-07-22 13:22:46
import { OptionRule } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type OptionRuleAttributes = Omit<OptionRule, "id" | "createdAt" | "updatedAt">;

export class OptionRuleService extends BaseService<OptionRule> {
	protected model = prisma.optionRule;
	protected entityName = "OptionRule";
	protected modelName = "optionRule";

	protected async validate(entity: OptionRuleAttributes): Promise<void> {
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.priority) throw new BadRequestError("priority is required");
		if (!entity.isActive) throw new BadRequestError("isActive is required");
		if (!entity.condition) throw new BadRequestError("condition is required");
	}
}