// This file was generated by generate-services.ts on 2025-08-26 14:00:06
import type { OptionRuleTrigger } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type OptionRuleTriggerAttributes = Omit<OptionRuleTrigger, "id" | "createdAt" | "updatedAt">;

export class OptionRuleTriggerService extends BaseService<OptionRuleTrigger> {
  protected model = prisma.optionRuleTrigger;
  protected entityName = "OptionRuleTrigger";
  protected modelName = "optionRuleTrigger";

  protected async validate(entity: OptionRuleTriggerAttributes): Promise<void> {
    if (!entity.ruleId)
      throw new BadRequestError("ruleId is required");
    if (!entity.optionId)
      throw new BadRequestError("optionId is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
