// This file was generated by generate-services.ts on 2025-07-22 11:15:21
import { OptionHeader } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type OptionHeaderAttributes = Omit<OptionHeader, "id" | "createdAt" | "updatedAt">;

export class OptionHeaderService extends BaseService<OptionHeader> {
	protected model = prisma.optionHeader;
	protected entityName = "OptionHeader";
	protected modelName = "optionHeader";

	protected async validate(entity: OptionHeaderAttributes): Promise<void> {
		if (!entity.categoryId) throw new BadRequestError("categoryId is required");
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.code) throw new BadRequestError("code is required");
	}
}
