// This file was generated by generate-services.ts on 2025-07-24 14:16:48
import { OptionRuleTarget } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type OptionRuleTargetAttributes = Omit<OptionRuleTarget, "id" | "createdAt" | "updatedAt">;

export class OptionRuleTargetService extends BaseService<OptionRuleTarget> {
	protected model = prisma.optionRuleTarget;
	protected entityName = "OptionRuleTarget";
	protected modelName = "optionRuleTarget";

	protected async validate(entity: OptionRuleTargetAttributes): Promise<void> {
		if (!entity.ruleId) throw new BadRequestError("ruleId is required");
		if (!entity.optionId) throw new BadRequestError("optionId is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}
}