// This file was generated by generate-services.ts on 2025-07-22 11:15:21
import { OptionCategory } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type OptionCategoryAttributes = Omit<OptionCategory, "id" | "createdAt" | "updatedAt">;

export class OptionCategoryService extends BaseService<OptionCategory> {
	protected model = prisma.optionCategory;
	protected entityName = "OptionCategory";
	protected modelName = "optionCategory";

	protected async validate(entity: OptionCategoryAttributes): Promise<void> {
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.allowMultiple) throw new BadRequestError("allowMultiple is required");
		if (!entity.isActive) throw new BadRequestError("isActive is required");
	}
}
