// This file was generated by generate-services.ts on 2025-08-26 10:53:59
import type { PerformanceSheetLink } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type PerformanceSheetLinkAttributes = Omit<PerformanceSheetLink, "id" | "createdAt" | "updatedAt">;

export class PerformanceSheetLinkService extends BaseService<PerformanceSheetLink> {
  protected model = prisma.performanceSheetLink;
  protected entityName = "PerformanceSheetLink";
  protected modelName = "performanceSheetLink";

  protected async validate(entity: PerformanceSheetLinkAttributes): Promise<void> {
    if (!entity.performanceSheetId)
      throw new BadRequestError("performanceSheetId is required");
    if (!entity.entityType)
      throw new BadRequestError("entityType is required");
    if (!entity.entityId)
      throw new BadRequestError("entityId is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
