// This file was generated by generate-services.ts on 2025-09-05 18:23:29
import type { PerformanceSheetVersion } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type PerformanceSheetVersionAttributes = Omit<PerformanceSheetVersion, "id" | "createdAt" | "updatedAt">;

export class PerformanceSheetVersionService extends BaseService<PerformanceSheetVersion> {
  protected model = prisma.performanceSheetVersion;
  protected entityName = "PerformanceSheetVersion";
  protected modelName = "performanceSheetVersion";

  protected async validate(entity: PerformanceSheetVersionAttributes): Promise<void> {
    if (!entity.sections)
      throw new BadRequestError("sections is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
