// This file was generated by generate-services.ts on 2025-07-22 10:23:15
import { PerformanceSheet } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type PerformanceSheetAttributes = Omit<PerformanceSheet, "id" | "createdAt" | "updatedAt">;

export class PerformanceSheetService extends BaseService<PerformanceSheet> {
	protected model = prisma.performanceSheet;
	protected entityName = "PerformanceSheet";
	protected modelName = "performanceSheet";

	protected async validate(entity: PerformanceSheetAttributes): Promise<void> {
		if (!entity.versionId) throw new BadRequestError("versionId is required");
		if (!entity.referenceNumber) throw new BadRequestError("referenceNumber is required");
		if (!entity.revisionNumber) throw new BadRequestError("revisionNumber is required");
		if (!entity.data) throw new BadRequestError("data is required");
	}
}
