// This file was generated by generate-services.ts
import type { Permission } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type PermissionAttributes = Omit<Permission, "id" | "createdAt" | "updatedAt">;

export class PermissionService extends BaseService<Permission> {
  protected model = prisma.permission;
  protected entityName = "Permission";
  protected modelName = "permission";

  protected async validate(entity: PermissionAttributes): Promise<void> {
    if (!entity.resource)
      throw new BadRequestError("resource is required");
    if (!entity.action)
      throw new BadRequestError("action is required");
  }
}
