// This file was generated by generate-services.ts on 2025-09-05 18:23:29
import type { ProductClass } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type ProductClassAttributes = Omit<ProductClass, "id" | "createdAt" | "updatedAt">;

export class ProductClassService extends BaseService<ProductClass> {
  protected model = prisma.productClass;
  protected entityName = "ProductClass";
  protected modelName = "productClass";

  protected async validate(entity: ProductClassAttributes): Promise<void> {
    if (!entity.code)
      throw new BadRequestError("code is required");
    if (!entity.name)
      throw new BadRequestError("name is required");
    if (!entity.depth)
      throw new BadRequestError("depth is required");
    if (!entity.isActive)
      throw new BadRequestError("isActive is required");
  }
}
