// This file was generated by generate-services.ts on 2025-09-02 08:45:51
import { ProductClassOptionCategory } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type ProductClassOptionCategoryAttributes = Omit<ProductClassOptionCategory, "id" | "createdAt" | "updatedAt">;

export class ProductClassOptionCategoryService extends BaseService<ProductClassOptionCategory> {
	protected model = prisma.productClassOptionCategory;
	protected entityName = "ProductClassOptionCategory";
	protected modelName = "productClassOptionCategory";

	protected async validate(entity: ProductClassOptionCategoryAttributes): Promise<void> {
		if (!entity.productClassId) throw new BadRequestError("productClassId is required");
		if (!entity.optionCategoryId) throw new BadRequestError("optionCategoryId is required");
		if (!entity.displayOrder) throw new BadRequestError("displayOrder is required");
		if (!entity.isRequired) throw new BadRequestError("isRequired is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}
}