// This file was generated by generate-services.ts on 2025-09-02 08:45:51
import { QuoteTerms } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type QuoteTermsAttributes = Omit<QuoteTerms, "id" | "createdAt" | "updatedAt">;

export class QuoteTermsService extends BaseService<QuoteTerms> {
	protected model = prisma.quoteTerms;
	protected entityName = "QuoteTerms";
	protected modelName = "quoteTerms";

	protected async validate(entity: QuoteTermsAttributes): Promise<void> {
		if (!entity.quoteDetailsId) throw new BadRequestError("quoteDetailsId is required");
		if (!entity.netDays) throw new BadRequestError("netDays is required");
	}
}