// This file was generated by generate-services.ts on 2025-09-02 08:45:51
import { QuoteHeader } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type QuoteHeaderAttributes = Omit<QuoteHeader, "id" | "createdAt" | "updatedAt">;

export class QuoteHeaderService extends BaseService<QuoteHeader> {
	protected model = prisma.quoteHeader;
	protected entityName = "QuoteHeader";
	protected modelName = "quoteHeader";

	protected async validate(entity: QuoteHeaderAttributes): Promise<void> {
		if (!entity.year) throw new BadRequestError("year is required");
		if (!entity.number) throw new BadRequestError("number is required");
		if (!entity.priority) throw new BadRequestError("priority is required");
		if (!entity.confidence) throw new BadRequestError("confidence is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
		if (!entity.legacy) throw new BadRequestError("legacy is required");
	}
}