// This file was generated by generate-services.ts on 2025-09-05 18:23:29
import type { QuoteTerms } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type QuoteTermsAttributes = Omit<QuoteTerms, "id" | "createdAt" | "updatedAt">;

export class QuoteTermsService extends BaseService<QuoteTerms> {
  protected model = prisma.quoteTerms;
  protected entityName = "QuoteTerms";
  protected modelName = "quoteTerms";

  protected async validate(entity: QuoteTermsAttributes): Promise<void> {
    if (!entity.quoteDetailsId)
      throw new BadRequestError("quoteDetailsId is required");
    if (!entity.netDays)
      throw new BadRequestError("netDays is required");
  }
}
