// This file was generated by generate-services.ts on 2025-09-02 13:16:58
import { QuoteNote } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type QuoteNoteAttributes = Omit<QuoteNote, "id" | "createdAt" | "updatedAt">;

export class QuoteNoteService extends BaseService<QuoteNote> {
	protected model = prisma.quoteNote;
	protected entityName = "QuoteNote";
	protected modelName = "quoteNote";

	protected async validate(entity: QuoteNoteAttributes): Promise<void> {
		if (!entity.quoteDetailsId) throw new BadRequestError("quoteDetailsId is required");
		if (!entity.body) throw new BadRequestError("body is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}
}