// This file was generated by generate-services.ts on 2025-08-26 14:00:06
import type { QuoteItem } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type QuoteItemAttributes = Omit<QuoteItem, "id" | "createdAt" | "updatedAt">;

export class QuoteItemService extends BaseService<QuoteItem> {
  protected model = prisma.quoteItem;
  protected entityName = "QuoteItem";
  protected modelName = "quoteItem";

  protected async validate(entity: QuoteItemAttributes): Promise<void> {
    if (!entity.quoteId)
      throw new BadRequestError("quoteId is required");
    if (!entity.quantity)
      throw new BadRequestError("quantity is required");
    if (!entity.unitPrice)
      throw new BadRequestError("unitPrice is required");
    if (!entity.totalPrice)
      throw new BadRequestError("totalPrice is required");
    if (!entity.lineNumber)
      throw new BadRequestError("lineNumber is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
