// This file was generated by generate-services.ts on 2025-07-22 11:23:05
import { QuoteItem } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type QuoteItemAttributes = Omit<QuoteItem, "id" | "createdAt" | "updatedAt">;

export class QuoteItemService extends BaseService<QuoteItem> {
	protected model = prisma.quoteItem;
	protected entityName = "QuoteItem";
	protected modelName = "quoteItem";

	protected async validate(entity: QuoteItemAttributes): Promise<void> {
		if (!entity.quoteId) throw new BadRequestError("quoteId is required");
		if (!entity.quantity) throw new BadRequestError("quantity is required");
		if (!entity.unitPrice) throw new BadRequestError("unitPrice is required");
		if (!entity.totalPrice) throw new BadRequestError("totalPrice is required");
		if (!entity.lineNumber) throw new BadRequestError("lineNumber is required");
	}
}
