// This file was generated by generate-services.ts on 2025-09-02 08:45:51
import { QuoteDetails } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type QuoteDetailsAttributes = Omit<QuoteDetails, "id" | "createdAt" | "updatedAt">;

export class QuoteDetailsService extends BaseService<QuoteDetails> {
	protected model = prisma.quoteDetails;
	protected entityName = "QuoteDetails";
	protected modelName = "quoteDetails";

	protected async validate(entity: QuoteDetailsAttributes): Promise<void> {
		if (!entity.quoteHeaderId) throw new BadRequestError("quoteHeaderId is required");
		if (!entity.revision) throw new BadRequestError("revision is required");
		if (!entity.createdById) throw new BadRequestError("createdById is required");
		if (!entity.updatedById) throw new BadRequestError("updatedById is required");
	}
}