// This file was generated by generate-services.ts
import type { QuoteRevision } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type QuoteRevisionAttributes = Omit<QuoteRevision, "id" | "createdAt" | "updatedAt">;

export class QuoteRevisionService extends BaseService<QuoteRevision> {
  protected model = prisma.quoteRevision;
  protected entityName = "QuoteRevision";
  protected modelName = "quoteRevision";

  protected async validate(entity: QuoteRevisionAttributes): Promise<void> {
    if (!entity.quoteHeaderId)
      throw new BadRequestError("quoteHeaderId is required");
    if (!entity.revision)
      throw new BadRequestError("revision is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
