// This file was generated by generate-services.ts on 2025-08-25 15:13:33
import type { Quote } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type QuoteAttributes = Omit<Quote, "id" | "createdAt" | "updatedAt">;

export class QuoteService extends BaseService<Quote> {
  protected model = prisma.quote;
  protected entityName = "Quote";
  protected modelName = "quote";

  protected async validate(entity: QuoteAttributes): Promise<void> {
    if (!entity.year)
      throw new BadRequestError("year is required");
    if (!entity.number)
      throw new BadRequestError("number is required");
    if (!entity.revision)
      throw new BadRequestError("revision is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
