// This file was generated by generate-services.ts
import type { QuoteDetails } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type QuoteDetailsAttributes = Omit<QuoteDetails, "id" | "createdAt" | "updatedAt">;

export class QuoteDetailsService extends BaseService<QuoteDetails> {
  protected model = prisma.quoteDetails;
  protected entityName = "QuoteDetails";
  protected modelName = "quoteDetails";

  protected async validate(entity: QuoteDetailsAttributes): Promise<void> {
    if (!entity.quoteHeaderId)
      throw new BadRequestError("quoteHeaderId is required");
    if (!entity.revision)
      throw new BadRequestError("revision is required");
    if (!entity.createdById)
      throw new BadRequestError("createdById is required");
    if (!entity.updatedById)
      throw new BadRequestError("updatedById is required");
  }
}
