// This file was generated by generate-services.ts
import type { Role } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type RoleAttributes = Omit<Role, "id" | "createdAt" | "updatedAt">;

export class RoleService extends BaseService<Role> {
  protected model = prisma.role;
  protected entityName = "Role";
  protected modelName = "role";

  protected async validate(entity: RoleAttributes): Promise<void> {
    if (!entity.name)
      throw new BadRequestError("name is required");
    if (!entity.isSystem)
      throw new BadRequestError("isSystem is required");
  }
}
