// This file was generated by generate-services.ts on 2025-08-26 14:00:06
import { Role } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type RoleAttributes = Omit<Role, "id" | "createdAt" | "updatedAt">;

export class RoleService extends BaseService<Role> {
	protected model = prisma.role;
	protected entityName = "Role";
	protected modelName = "role";

	protected async validate(entity: RoleAttributes): Promise<void> {
		if (!entity.name) throw new BadRequestError("name is required");
		if (!entity.isSystem) throw new BadRequestError("isSystem is required");
	}
}