// This file was generated by generate-services.ts on 2025-08-26 14:00:06
import { RolePermission } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type RolePermissionAttributes = Omit<RolePermission, "id" | "createdAt" | "updatedAt">;

export class RolePermissionService extends BaseService<RolePermission> {
	protected model = prisma.rolePermission;
	protected entityName = "RolePermission";
	protected modelName = "rolePermission";

	protected async validate(entity: RolePermissionAttributes): Promise<void> {
		if (!entity.roleId) throw new BadRequestError("roleId is required");
		if (!entity.permissionId) throw new BadRequestError("permissionId is required");
	}
}