// This file was generated by generate-services.ts
import type { SubmissionAnswer } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type SubmissionAnswerAttributes = Omit<SubmissionAnswer, "id" | "createdAt" | "updatedAt">;

export class SubmissionAnswerService extends BaseService<SubmissionAnswer> {
  protected model = prisma.submissionAnswer;
  protected entityName = "SubmissionAnswer";
  protected modelName = "submissionAnswer";

  protected async validate(entity: SubmissionAnswerAttributes): Promise<void> {
    if (!entity.submissionId)
      throw new BadRequestError("submissionId is required");
    if (!entity.fieldId)
      throw new BadRequestError("fieldId is required");
  }
}
