// This file was generated by generate-services.ts
import type { Tag } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type TagAttributes = Omit<Tag, "id" | "createdAt" | "updatedAt">;

export class TagService extends BaseService<Tag> {
  protected model = prisma.tag;
  protected entityName = "Tag";
  protected modelName = "tag";

  protected async validate(entity: TagAttributes): Promise<void> {
    if (!entity.description)
      throw new BadRequestError("description is required");
    if (!entity.parentTable)
      throw new BadRequestError("parentTable is required");
    if (!entity.parentId)
      throw new BadRequestError("parentId is required");
    if (!entity.createdBy)
      throw new BadRequestError("createdBy is required");
  }
}
