// This file was generated by generate-services.ts on 2025-08-25 15:13:33
import type { User } from "@prisma/client";

import { BadRequestError } from "@/middleware/error.middleware";
import { prisma } from "@/utils/prisma";

import { BaseService } from "./_base.service";

type UserAttributes = Omit<User, "id" | "createdAt" | "updatedAt">;

export class UserService extends BaseService<User> {
  protected model = prisma.user;
  protected entityName = "User";
  protected modelName = "user";

  protected async validate(entity: UserAttributes): Promise<void> {
    if (!entity.username)
      throw new BadRequestError("username is required");
    if (!entity.isActive)
      throw new BadRequestError("isActive is required");
  }
}
