// This file was generated by generate-services.ts on 2025-07-22 11:15:21
import { User } from "@prisma/client";
import { BaseService } from "./_base.service";
import { prisma } from "@/utils/prisma";
import { BadRequestError } from "@/middleware/error.middleware";

type UserAttributes = Omit<User, "id" | "createdAt" | "updatedAt">;

export class UserService extends BaseService<User> {
	protected model = prisma.user;
	protected entityName = "User";
	protected modelName = "user";

	protected async validate(entity: UserAttributes): Promise<void> {
		if (!entity.username) throw new BadRequestError("username is required");
		if (!entity.isActive) throw new BadRequestError("isActive is required");
	}
}
