name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_DEPLOY_KEY }}" > ~/.ssh/pi_deploy_key
          chmod 600 ~/.ssh/pi_deploy_key
          echo "${{ secrets.PI_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to /server
        run: |
          rsync -avz --delete \
            --exclude '.git*' \
            --exclude 'node_modules' \
            -e "ssh -i ~/.ssh/pi_deploy_key -o StrictHostKeyChecking=yes" \
            ./apps/server/ ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }}:/server/

      - name: Restart systemd service
        run: |
          ssh -i ~/.ssh/pi_deploy_key -o StrictHostKeyChecking=yes ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "
            sudo systemctl restart server
          "

